# SPDX-License-Identifier: AGPL-3.0-or-later
"""D language analysis pass using tree-sitter.

Detects:
- Module declarations
- Import statements
- Function definitions (top-level)
- Method definitions (inside struct/class/interface, qualified names)
- Struct definitions
- Class definitions
- Interface definitions

D is a systems programming language that combines low-level control
with modern features like garbage collection, closures, and ranges.
The tree-sitter-d parser handles .d and .di (interface) files.

How It Works
------------
Uses TreeSitterAnalyzer base class for two-pass orchestration:
1. Pass 1: Extract module, function, struct, class, interface symbols
2. Pass 2: Extract import edges and call edges using NameResolver

The base class handles grammar checking, parser creation, file discovery,
and result assembly. This module provides only the D-specific extraction
logic.

Why This Design
---------------
- TreeSitterAnalyzer eliminates ~150 lines of boilerplate
- Optional dependency keeps base install lightweight
- Uses tree-sitter-language-pack for D grammar
- D is used for systems programming as a modern C++ alternative
- Supports both source (.d) and interface (.di) files
- Methods use qualified names to enable containment linking
"""
from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, ClassVar, Iterator, Optional

from hypergumbo_core.analyze.base import (
    AnalysisResult,
    FileAnalysis,
    TreeSitterAnalyzer,
    find_child_by_type,
    iter_tree,
    make_symbol_id,
    make_unresolved_edge,
    node_text,
)
from hypergumbo_core.discovery import classify_dot_d_file, find_files
from hypergumbo_core.ir import Edge, Span, Symbol, make_pass_id
from hypergumbo_core.symbol_resolution import NameResolver
from hypergumbo_core.analyze.registry import register_analyzer
from hypergumbo_core.analyze.cyclomatic import compute_cyclomatic_complexity

if TYPE_CHECKING:
    import tree_sitter
    from hypergumbo_core.ir import AnalysisRun

PASS_ID = make_pass_id("d")


def find_d_files(repo_root: Path) -> Iterator[Path]:
    """Find all D language files in the repository.

    Filters out GCC Makefile dependency files (``.d`` generated by
    ``gcc -MMD``) using content-based classification.  ``.di`` files
    (D interface files) are always included without classification.
    """
    for path in find_files(repo_root, ["*.d", "*.di"]):
        if classify_dot_d_file(path) == "d":
            yield path


# ---------------------------------------------------------------------------
# Symbol extraction helpers
# ---------------------------------------------------------------------------


def _make_symbol(
    rel_path: str, run_id: str, node: "tree_sitter.Node",
    name: str, kind: str, source: bytes,
    analyzer: "DAnalyzer",
    signature: Optional[str] = None, meta: Optional[dict] = None,
) -> Symbol:
    """Create a Symbol with consistent formatting."""
    start_line = node.start_point[0] + 1
    end_line = node.end_point[0] + 1
    # INV-loguk: CC only for callables; module/struct/class/interface funnel
    # through this same helper and would otherwise aggregate their subtrees.
    _is_callable = kind in ("function", "method")
    span = Span(
        start_line=start_line,
        start_col=node.start_point[1],
        end_line=end_line,
        end_col=node.end_point[1],
    )
    return Symbol(
        id=make_symbol_id("d", rel_path, start_line, end_line, name, kind),
        name=name,
        kind=kind,
        language="d",
        path=rel_path,
        span=span,
        origin=PASS_ID,
        origin_run_id=run_id,
        # WI-bokab (v7): fold this file's identity into the containing slot so two
        # symbols with the same (kind, name) in different files hash distinctly.
        # ``rel_path`` is the repo-relative path threaded from
        # extract_symbols_from_file(..., rel_path, ...); the base helper normalizes it.
        stable_id=analyzer.compute_stable_id(
            node, kind=kind, name=name,
            file_stable_id=analyzer._file_anchor(rel_path),
        ),
        signature=signature,
        meta=meta,
        cyclomatic_complexity=(
            compute_cyclomatic_complexity(node, "d") if _is_callable else None
        ),
        line_span=(end_line - start_line + 1) if _is_callable else None,
    )


def _process_module_declaration(
    source: bytes, rel_path: str, run_id: str, node: "tree_sitter.Node",
    analyzer: "DAnalyzer",
) -> Optional[Symbol]:
    """Process a module declaration."""
    fqn = find_child_by_type(node, "module_fqn")
    if not fqn:
        return None  # pragma: no cover - defensive

    mod_name = node_text(fqn, source)
    return _make_symbol(rel_path, run_id, node, mod_name, "module", source, analyzer)


_CONTAINER_NODE_TYPES = frozenset({
    "struct_declaration", "class_declaration", "interface_declaration",
    # A NAMED union owns its members (a nested type: `U.a`, not `Outer.a`). An
    # ANONYMOUS union has no ``identifier`` child, so ``_find_parent_container``'s
    # ``if name_node`` guard skips it and the walk continues to the enclosing
    # struct — correctly preserving D's anonymous-union member hoisting.
    "union_declaration",
})


def _find_parent_container(
    node: "tree_sitter.Node", source: bytes
) -> Optional[str]:
    """Walk up to find the enclosing struct/class/interface name."""
    current = node.parent
    while current is not None:
        if current.type in _CONTAINER_NODE_TYPES:
            name_node = find_child_by_type(current, "identifier")
            if name_node:
                return node_text(name_node, source)
        current = current.parent
    return None


def _process_function_declaration(
    source: bytes, rel_path: str, run_id: str, node: "tree_sitter.Node",
    analyzer: "DAnalyzer",
) -> Optional[Symbol]:
    """Process a function declaration.

    If the function is inside a struct, class, or interface, it is
    extracted as a method with a qualified name (e.g., ``Searcher.search``).
    Top-level functions keep ``kind="function"``.
    """
    name_node = find_child_by_type(node, "identifier")
    if not name_node:
        return None  # pragma: no cover - defensive

    func_name = node_text(name_node, source)

    # Get parameters for signature
    params = find_child_by_type(node, "parameters")
    signature = node_text(params, source) if params else "()"

    # Check if function is inside a container (struct/class/interface)
    parent_name = _find_parent_container(node, source)
    if parent_name:
        qualified_name = f"{parent_name}.{func_name}"
        return _make_symbol(rel_path, run_id, node, qualified_name, "method", source, analyzer, signature=signature)
    else:
        # WI-situj: stamp the first-parameter type so the receiver_type_dispatch
        # linker can recover UFCS calls (``x.func()`` ≡ ``func(x)``) against it.
        fn_meta: dict = {}
        first_type = _first_param_type(node, source)
        if first_type:
            fn_meta["ufcs_receiver_type"] = first_type
        # INV-fahub (real-repro dub residual): a NESTED-LOCAL function — declared
        # inside another function's body — is not callable by bare name from
        # outside its enclosing scope, so it must not become a global resolver
        # target (the ``exists(x)`` free-call funnel that bound to utils.d's
        # nested ``exists``). Mark it so ``register_symbol`` keeps it out of the
        # resolver index; it still ships as an output symbol.
        if _enclosing_function_node(node) is not None:
            fn_meta["nested_local"] = True
        return _make_symbol(rel_path, run_id, node, func_name, "function", source, analyzer, signature=signature, meta=fn_meta or None)


def _process_struct_declaration(
    source: bytes, rel_path: str, run_id: str, node: "tree_sitter.Node",
    analyzer: "DAnalyzer",
) -> Optional[Symbol]:
    """Process a struct declaration."""
    name_node = find_child_by_type(node, "identifier")
    if not name_node:
        return None  # pragma: no cover - defensive

    struct_name = node_text(name_node, source)
    return _make_symbol(rel_path, run_id, node, struct_name, "struct", source, analyzer)


def _process_class_declaration(
    source: bytes, rel_path: str, run_id: str, node: "tree_sitter.Node",
    analyzer: "DAnalyzer",
) -> Optional[Symbol]:
    """Process a class declaration."""
    name_node = find_child_by_type(node, "identifier")
    if not name_node:
        return None  # pragma: no cover - defensive

    class_name = node_text(name_node, source)
    return _make_symbol(rel_path, run_id, node, class_name, "class", source, analyzer)


def _process_interface_declaration(
    source: bytes, rel_path: str, run_id: str, node: "tree_sitter.Node",
    analyzer: "DAnalyzer",
) -> Optional[Symbol]:
    """Process an interface declaration."""
    name_node = find_child_by_type(node, "identifier")
    if not name_node:
        return None  # pragma: no cover - defensive

    iface_name = node_text(name_node, source)
    return _make_symbol(rel_path, run_id, node, iface_name, "interface", source, analyzer)


# ---------------------------------------------------------------------------
# Field / variable extraction helpers (WI-jusus)
# ---------------------------------------------------------------------------

_D_VALUE_DECL_NODES = frozenset({"variable_declaration", "auto_declaration"})


def _iter_d_declarator_names(
    node: "tree_sitter.Node",
) -> Iterator["tree_sitter.Node"]:
    """Yield the name ``identifier`` node for each declared name.

    A ``variable_declaration`` lists one ``declarator`` per name (multi-name
    ``int a, b;``); an ``auto_declaration`` (``auto x = …``) carries the name
    identifier directly.
    """
    if node.type == "auto_declaration":
        ident = find_child_by_type(node, "identifier")
        if ident is not None:
            yield ident
        return
    for child in node.children:
        if child.type == "declarator":
            ident = find_child_by_type(child, "identifier")
            if ident is not None:
                yield ident


def _process_value_declaration(
    source: bytes, rel_path: str, run_id: str, node: "tree_sitter.Node",
    analyzer: "DAnalyzer",
) -> list[tuple[Symbol, "tree_sitter.Node"]]:
    """Emit a ``variable_declaration`` / ``auto_declaration`` as field or variable.

    The same node type serves a struct/class field, a module global, AND a
    function-body local, so classify by the IMMEDIATE parent: ``aggregate_body``
    → **field** (owner = the enclosing struct/class/interface, via the existing
    ``_find_parent_container`` — so a nested struct's member is owned by the
    nearest type, ``Inner.x`` not ``Outer.x``); module scope (``module_def`` when
    a ``module X;`` declaration is present, else ``source_file`` directly) →
    **variable**; anything else (``block_statement``/``function_body``) → skipped
    local. Data anchors only — never call/instantiate targets.
    """
    parent = node.parent
    if parent is None:
        return []  # pragma: no cover - defensive
    if parent.type == "aggregate_body":
        owner = _find_parent_container(node, source)
        if owner is None:
            return []  # pragma: no cover - defensive
        kind = "field"
        prefix = f"{owner}."
    elif parent.type in ("module_def", "source_file"):
        kind = "variable"
        prefix = ""
    else:
        return []  # a function-body local (or other nested scope) — not emitted
    pairs: list[tuple[Symbol, "tree_sitter.Node"]] = []
    for name_node in _iter_d_declarator_names(node):
        name = prefix + node_text(name_node, source)
        sym = _make_symbol(rel_path, run_id, name_node, name, kind, source, analyzer)
        pairs.append((sym, name_node))
    return pairs


def _process_enum_member(
    source: bytes, rel_path: str, run_id: str, node: "tree_sitter.Node",
    analyzer: "DAnalyzer",
) -> Optional[Symbol]:
    """Emit an ``enum_member`` as a ``kind="field"`` anchor (``Color.red``).

    Enum members are type members accessed via ``.`` (dart/zig/nim precedent);
    the owner is the enclosing ``enum_declaration``'s name. An ANONYMOUS enum
    (``enum { A, B }``) parses to a distinct ``anonymous_enum_declaration`` node
    with no owner name, so its members are skipped (a fails-safe recall miss,
    never a wrong-owner phantom).
    """
    enum_decl = node.parent
    # node.parent is Node | None; a None parent (root node) has no owner, which
    # is the same fails-safe skip as a non-enum_declaration parent.
    if enum_decl is None or enum_decl.type != "enum_declaration":
        return None  # anonymous_enum_declaration (or other) — no owner, skip
    name_node = find_child_by_type(enum_decl, "identifier")
    if name_node is None:
        return None  # pragma: no cover - a named enum_declaration always names
    ident = find_child_by_type(node, "identifier")
    if ident is None:
        return None  # pragma: no cover - defensive
    owner = node_text(name_node, source)
    member = node_text(ident, source)
    return _make_symbol(
        rel_path, run_id, node, f"{owner}.{member}", "field", source, analyzer,
    )


# ---------------------------------------------------------------------------
# Import alias and edge extraction helpers
# ---------------------------------------------------------------------------


def _extract_import_aliases(
    tree: "tree_sitter.Tree",
    source: bytes,
) -> dict[str, str]:
    """Extract import aliases for disambiguation.

    In D:
        import math = std.math; -> math maps to std.math

    Returns a dict mapping alias names to module paths.
    """
    aliases: dict[str, str] = {}

    for node in iter_tree(tree.root_node):
        if node.type != "import_declaration":
            continue

        # Find imported node containing alias = module_fqn
        imported = find_child_by_type(node, "imported")
        if not imported:  # pragma: no cover - defensive
            continue

        # Check if there's an alias (identifier before =)
        alias_name = None
        module_path = None

        for child in imported.children:
            if child.type == "identifier":
                alias_name = node_text(child, source)
            elif child.type == "module_fqn":
                module_path = node_text(child, source)

        if alias_name and module_path:
            aliases[alias_name] = module_path

    return aliases


def _extract_imported_modules(
    tree: "tree_sitter.Tree",
    source: bytes,
) -> list[str]:
    """Extract all imported module paths for import-scope disambiguation.

    In D, ``import errors;`` makes all public symbols from the ``errors``
    module available in the current scope.  When resolving a bare call
    like ``error()``, we prefer symbols from imported modules over
    identically-named symbols in unrelated files.

    Returns a list of module path strings converted to file-path style
    (dots replaced with ``/``), e.g. ``["errors", "dmd/errors"]``.
    """
    modules: list[str] = []

    for node in iter_tree(tree.root_node):
        if node.type != "import_declaration":
            continue

        imported = find_child_by_type(node, "imported")
        if not imported:  # pragma: no cover - defensive
            continue

        fqn = find_child_by_type(imported, "module_fqn")
        if not fqn:
            continue  # pragma: no cover - defensive

        module_name = node_text(fqn, source)
        # Convert D module path (dots) to file path (slashes)
        # e.g., "dmd.errors" -> "dmd/errors"
        modules.append(module_name.replace(".", "/"))

    return modules


def _process_import_declaration(
    source: bytes,
    file_stable_id: str,
    run_id: str,
    node: "tree_sitter.Node",
    module_registry: dict[str, str] | None = None,
) -> list[Edge]:
    """Process an import declaration.

    When *module_registry* maps module names to their symbol IDs, the
    dst of the import edge is resolved to the actual module symbol.
    Otherwise, the dst is the well-formed external-module id
    ``d:{module}:0-0:module:module`` (module in the path slot, INV-fihur)
    used for external / standard-library imports.
    """
    edges: list[Edge] = []

    imported = find_child_by_type(node, "imported")
    if not imported:
        return edges  # pragma: no cover - defensive

    fqn = find_child_by_type(imported, "module_fqn")
    if not fqn:
        return edges  # pragma: no cover - defensive

    import_name = node_text(fqn, source)

    # Resolve to actual module symbol if available
    if module_registry and import_name in module_registry:
        dst = module_registry[import_name]
        confidence = 0.95
    else:
        dst = f"d:{import_name}:0-0:module:module"
        confidence = 0.9

    edges.append(
        Edge.create(
            src=file_stable_id,
            dst=dst,
            edge_type="imports",
            line=node.start_point[0] + 1,
            confidence=confidence,
            origin=PASS_ID,
            origin_run_id=run_id,
        )
    )
    return edges


def _find_enclosing_function_d(
    node: "tree_sitter.Node",
    source: bytes,
    local_symbols: dict[str, Symbol],
) -> Optional[Symbol]:
    """Find the enclosing function Symbol by walking up parents.

    For methods inside structs/classes/interfaces, the local_symbols map
    uses qualified names (e.g., ``Searcher.search``), so we build the
    qualified name when the enclosing function is inside a container.
    """
    current = node.parent
    while current is not None:
        if current.type == "function_declaration":
            name_node = find_child_by_type(current, "identifier")
            if name_node:
                name = node_text(name_node, source)
                # Try bare name first (top-level function)
                sym = local_symbols.get(name)
                if sym:
                    return sym
                # Try qualified name (method inside container)
                parent_name = _find_parent_container(current, source)
                if parent_name:
                    sym = local_symbols.get(f"{parent_name}.{name}")
                    if sym:
                        return sym
        current = current.parent
    return None  # pragma: no cover - defensive


def _get_call_target_name_d(
    node: "tree_sitter.Node", source: bytes
) -> tuple[Optional[str], Optional[str]]:
    """Extract the target name and receiver from a call_expression.

    Handles three call patterns in D:
    1. ``writeln("hello")`` -> identifier child -> (writeln, None)
    2. ``errors.error("bad")`` -> type > identifier, '.', identifier -> (error, errors)
    3. ``to!string(42)`` -> type > template_instance > identifier -> (to, None)

    Returns (target_name, receiver) where receiver is the module prefix
    for qualified calls like math.sin().
    """
    for child in node.children:
        if child.type == "identifier":
            return (node_text(child, source), None)
        elif child.type == "type":
            # Check for template_instance first: to!string(42)
            for subchild in child.children:
                if subchild.type == "template_instance":
                    tmpl_name = find_child_by_type(subchild, "identifier")
                    if tmpl_name:
                        return (node_text(tmpl_name, source), None)
            # Qualified call like math.sin()
            # type has: identifier (math), '.', identifier (sin)
            parts = []
            for subchild in child.children:
                if subchild.type == "identifier":
                    parts.append(node_text(subchild, source))
            if len(parts) >= 2:
                return (parts[-1], parts[0])
            elif len(parts) == 1:  # pragma: no cover - defensive
                return (parts[0], None)
    return (None, None)  # pragma: no cover - defensive


def _get_ufcs_template_name(
    node: "tree_sitter.Node", source: bytes
) -> Optional[str]:
    """Extract the template function name from a UFCS property_expression.

    Handles patterns like ``arr.map!(a => a * 2)`` where the tree-sitter AST
    produces a ``property_expression`` with a ``template_instance`` child.

    Returns the function name (e.g., "map") or None if not a UFCS template.
    """
    for child in node.children:
        if child.type == "template_instance":
            tmpl_name = find_child_by_type(child, "identifier")
            if tmpl_name:
                return node_text(tmpl_name, source)
    return None


def _param_name_and_type(
    param_node: "tree_sitter.Node", source: bytes,
) -> tuple[Optional[str], Optional[str]]:
    """Return ``(param_name, base_type_name)`` for a D ``parameter`` node.

    A D ``parameter`` child has a ``type`` node (whose ``identifier`` is the
    type name, e.g. ``File``) followed by an ``identifier`` (the parameter
    name). ``base_type_name`` is ``None`` for an untyped / ``auto`` parameter
    so the caller records the name without a resolvable receiver type.
    """
    name: Optional[str] = None
    type_name: Optional[str] = None
    for child in param_node.children:
        if child.type == "identifier" and name is None:
            name = node_text(child, source)
        elif child.type == "type":
            tid = find_child_by_type(child, "identifier")
            if tid is not None:
                type_name = node_text(tid, source)
    return name, type_name


def _first_param_type(
    func_node: "tree_sitter.Node", source: bytes,
) -> Optional[str]:
    """Base type of a D function's FIRST parameter (its UFCS receiver type).

    ``bool exists(File f)`` → ``"File"``; a UFCS call ``x.exists()`` where ``x``
    has type ``File`` is sugar for ``exists(x)``, so the receiver-type-index
    linker (INV-vigaf) matches the call's ``receiver_type_hint`` against this.
    """
    params = find_child_by_type(func_node, "parameters")
    if params is None:  # pragma: no cover - function_declaration always has ()
        return None
    for child in params.children:
        if child.type == "parameter":
            _name, type_name = _param_name_and_type(child, source)
            return type_name
    return None


def _extract_param_var_types(
    func_node: "tree_sitter.Node", source: bytes,
) -> dict[str, Optional[str]]:
    """Map each parameter name to its base type (``None`` when untyped).

    WI-situj: the receiver of a UFCS call (``thing.exists()``) is most often a
    function parameter. Tracking parameter types lets the call site emit a
    ``receiver_type_hint`` (typed) or an un-hinted unresolved edge (auto),
    either way withholding the misbinding bare-name resolution. Local variable
    declarations and ``auto`` locals are a documented residual — not tracked
    here.
    """
    result: dict[str, Optional[str]] = {}
    params = find_child_by_type(func_node, "parameters")
    if params is None:  # pragma: no cover - function_declaration always has ()
        return result
    for child in params.children:
        if child.type == "parameter":
            name, type_name = _param_name_and_type(child, source)
            if name:
                result[name] = type_name
    return result


def _enclosing_function_node(
    node: "tree_sitter.Node",
) -> Optional["tree_sitter.Node"]:
    """Walk parents to the enclosing ``function_declaration`` node, or None."""
    current = node.parent
    while current is not None:
        if current.type == "function_declaration":
            return current
        current = current.parent
    return None


def _is_module_receiver(
    receiver: str,
    import_aliases: dict[str, str],
    imported_modules: list[str],
) -> bool:
    """Is a D call prefix ``P`` in ``P.name()`` a MODULE, or a VALUE (UFCS)?

    ``P`` is a module-qualified call (resolve normally) when it is an import alias
    or (the last segment of) an imported module path. Otherwise ``P`` is a value
    expression — a parameter, local, loop variable, or field — and ``P.name()`` is
    UFCS sugar for ``name(P)``; a bare short-name resolution of ``name`` would
    misbind to an arbitrary same-named internal free function (INV-fahub, the
    real-repro ``exists``/``startsWith``/``toString`` funnel on dub), so the caller
    withholds it and lets the ``receiver_type_dispatch`` linker (INV-vigaf) recover
    it from a ``receiver_type_hint`` when the value's type is known.
    """
    if receiver in import_aliases:
        return True
    for module in imported_modules:
        if module == receiver or module.rsplit(".", 1)[-1] == receiver:
            return True
    return False


def _resolve_and_emit_call_edge(
    caller: Symbol,
    target_name: str,
    receiver: Optional[str],
    import_aliases: dict[str, str],
    imported_modules: list[str],
    resolver: NameResolver,
    edges: list[Edge],
    node: "tree_sitter.Node",
    run_id: str,
    var_types: Optional[dict[str, Optional[str]]] = None,
) -> None:
    """Resolve a call target and emit a call edge.

    Shared between regular call_expression and UFCS property_expression
    handling. Uses import aliases for qualified calls and import-scope
    path_hints for bare calls to disambiguate cross-file resolution.
    """
    # WI-situj (INV-fahub / INV-vigaf): UFCS receiver gate. When the receiver is
    # a VALUE expression (any prefix that is not an imported module) — a
    # parameter, local, loop variable, or field — ``thing.exists()`` is NOT a
    # module-qualified call; it is UFCS sugar for ``exists(thing)``. The bare
    # ``resolver.lookup`` below would misbind it to an arbitrary same-named free
    # function ``exists()`` at 0.85 (real-repro dub funnel: ``startsWith`` /
    # ``toString`` / ``exists`` on locals & loop vars, not just parameters).
    # Instead emit the call unresolved with a ``receiver_type_hint`` when the
    # value's type is known (a typed parameter) and let the
    # ``receiver_type_dispatch`` linker recover the UFCS free function by matching
    # its first-parameter type; an untyped local / ``auto`` / builtin receiver
    # still withholds the misbind — the call stays honestly external.
    if receiver is not None and not _is_module_receiver(
        receiver, import_aliases, imported_modules,
    ):
        hint = var_types.get(receiver) if var_types else None
        edges.append(make_unresolved_edge(
            "d", caller.id, target_name,
            node.start_point[0] + 1, PASS_ID, run_id,
            receiver_type_hint=hint,
        ))
        return

    # Get path hint from import aliases if receiver is aliased
    path_hint: Optional[str] = None
    if receiver:
        path_hint = import_aliases.get(receiver)

    # Use resolver for callee resolution.  For bare calls
    # (no receiver), pass imported module paths as hints
    # so the resolver prefers symbols from imported modules
    # over identically-named symbols in unrelated files.
    hints = imported_modules if not receiver else None
    lookup_result = resolver.lookup(
        target_name,
        path_hint=path_hint,
        path_hints=hints,
    )
    if lookup_result.found and lookup_result.symbol:
        edges.append(Edge.create(
            src=caller.id,
            dst=lookup_result.symbol.id,
            edge_type="calls",
            line=node.start_point[0] + 1,
            confidence=0.85 * lookup_result.confidence,
            origin=PASS_ID,
            origin_run_id=run_id,
        ))
    else:
        # External function (e.g., writeln from std.stdio)
        edges.append(make_unresolved_edge(
            "d", caller.id, target_name,
            node.start_point[0] + 1,
            PASS_ID, run_id,
        ))


# ---------------------------------------------------------------------------
# DAnalyzer: TreeSitterAnalyzer subclass
# ---------------------------------------------------------------------------


class DAnalyzer(TreeSitterAnalyzer):
    """D language analyzer using tree-sitter-language-pack.

    D analysis has complex cross-file resolution requirements:
    - Module-qualified symbol registration for disambiguation
    - Import aliases for qualified call resolution
    - Import-scope path hints for bare call disambiguation
    - UFCS template call detection

    The base class handles grammar checking, parser creation, file discovery,
    timing, and result assembly. This subclass overrides register_symbol to
    use module-qualified names, and uses a custom resolver setup.
    """

    lang = "d"
    file_patterns: ClassVar[list[str]] = ["*.d", "*.di"]
    language_pack_name = "d"

    def extract_symbols_from_file(
        self, tree: "tree_sitter.Tree", source: bytes,
        file_path: Path, rel_path: str, run: "AnalysisRun",
    ) -> FileAnalysis:
        """Extract module, function, struct, class, interface, field, and variable symbols.

        WI-jusus: ``field`` (struct/class/enum members) and ``variable``
        (module-level globals) are DATA anchors — emitted to ``analysis.symbols``
        for search/centrality but kept out of the call graph (never added to
        ``symbol_by_name``; ``register_symbol`` skips them), so a bare-named
        module ``variable`` can never clobber a same-named ``function``.
        """
        analysis = FileAnalysis()

        for node in iter_tree(tree.root_node):
            pairs: list[tuple[Symbol, "tree_sitter.Node"]] = []
            if node.type == "module_declaration":
                sym = _process_module_declaration(source, rel_path, run.execution_id, node, self)
                if sym:
                    pairs.append((sym, node))
            elif node.type == "function_declaration":
                sym = _process_function_declaration(source, rel_path, run.execution_id, node, self)
                if sym:
                    pairs.append((sym, node))
            elif node.type == "struct_declaration":
                sym = _process_struct_declaration(source, rel_path, run.execution_id, node, self)
                if sym:
                    pairs.append((sym, node))
            elif node.type == "class_declaration":
                sym = _process_class_declaration(source, rel_path, run.execution_id, node, self)
                if sym:
                    pairs.append((sym, node))
            elif node.type == "interface_declaration":
                sym = _process_interface_declaration(source, rel_path, run.execution_id, node, self)
                if sym:
                    pairs.append((sym, node))
            elif node.type in _D_VALUE_DECL_NODES:
                pairs.extend(_process_value_declaration(source, rel_path, run.execution_id, node, self))
            elif node.type == "enum_member":
                sym = _process_enum_member(source, rel_path, run.execution_id, node, self)
                if sym:
                    pairs.append((sym, node))

            for sym, sym_node in pairs:
                analysis.symbols.append(sym)
                analysis.node_for_symbol[sym.id] = sym_node
                if sym.kind in ("function", "method"):
                    analysis.symbol_by_name[sym.name] = sym

        return analysis

    def get_import_aliases(
        self, tree: "tree_sitter.Tree", source: bytes,
    ) -> dict[str, str]:
        """Extract D import aliases (import alias = module)."""
        return _extract_import_aliases(tree, source)

    def register_symbol(
        self, symbol: Symbol, global_symbols: dict,
    ) -> None:
        """Register symbols with module-qualified names for disambiguation.

        This prevents name collisions: errors.error and unrelated.error
        both exist in the registry, enabling suffix matching with path
        hint disambiguation when the caller imports one module.

        WI-jusus: ``field``/``variable`` symbols are DATA anchors, never call or
        instantiation targets — skip them so a bare-named module ``variable``
        cannot clobber a same-named ``function``'s registry key (a false-negative
        an edge-site kind-gate cannot recover) and a field cannot shadow a real
        method. They still reach output/search/centrality because the output
        symbol set is built from ``analysis.symbols`` independently of this
        registry.
        """
        if symbol.kind in ("field", "variable"):
            return
        # INV-fahub: a nested-local function is not a cross-scope call target.
        if (symbol.meta or {}).get("nested_local"):
            return
        file_stem = Path(symbol.path).stem  # "errors.d" -> "errors"
        qualified = f"{file_stem}.{symbol.name}"
        global_symbols[qualified] = symbol
        # Also register unqualified for exact-match fallback
        # (last writer wins, but suffix matching has all)
        global_symbols[symbol.name] = symbol

    def extract_edges_from_file(
        self, tree: "tree_sitter.Tree", source: bytes,
        file_path: Path, rel_path: str,
        local_symbols: dict[str, Symbol], global_symbols: dict,
        run: "AnalysisRun", import_aliases: dict[str, str],
        resolver: "NameResolver",
    ) -> list[Edge]:
        """Extract import and call edges from a D file."""
        edges: list[Edge] = []
        file_stable_id = f"d:{rel_path}:file:"

        # Extract imported modules for scope-based disambiguation
        imported_modules = _extract_imported_modules(tree, source)

        # Build module registry for import edge resolution
        module_registry: dict[str, str] = {}
        for sym in global_symbols.values():
            if isinstance(sym, Symbol) and sym.kind == "module":
                module_registry[sym.name] = sym.id

        # WI-situj: per-function parameter var-types, computed lazily and keyed
        # by the enclosing function's byte span, so the UFCS receiver gate in
        # _resolve_and_emit_call_edge can tell a variable receiver from a module.
        var_types_cache: dict[tuple[int, int], dict[str, Optional[str]]] = {}

        for node in iter_tree(tree.root_node):
            # Process imports
            if node.type == "import_declaration":
                edges.extend(_process_import_declaration(
                    source, file_stable_id, run.execution_id, node, module_registry,
                ))

            # Process function calls
            elif node.type == "call_expression":
                target_name, receiver = _get_call_target_name_d(node, source)
                if target_name:
                    caller = _find_enclosing_function_d(node, source, local_symbols)
                    if caller:
                        fnode = _enclosing_function_node(node)
                        if fnode is None:  # pragma: no cover - caller ⟹ fnode set
                            call_var_types: dict[str, Optional[str]] = {}
                        else:
                            key = (fnode.start_byte, fnode.end_byte)
                            if key not in var_types_cache:
                                var_types_cache[key] = _extract_param_var_types(
                                    fnode, source,
                                )
                            call_var_types = var_types_cache[key]
                        _resolve_and_emit_call_edge(
                            caller, target_name, receiver,
                            import_aliases, imported_modules,
                            resolver, edges, node, run.execution_id,
                            var_types=call_var_types,
                        )

            # Process UFCS template calls: arr.map!(fn)
            elif node.type == "property_expression":
                ufcs_name = _get_ufcs_template_name(node, source)
                if ufcs_name:
                    caller = _find_enclosing_function_d(node, source, local_symbols)
                    if caller:
                        _resolve_and_emit_call_edge(
                            caller, ufcs_name, None,
                            import_aliases, imported_modules,
                            resolver, edges, node, run.execution_id,
                        )

        return edges


_analyzer = DAnalyzer()


def is_d_tree_sitter_available() -> bool:
    """Check if tree-sitter-d is available."""
    return _analyzer._check_grammar_available()


@register_analyzer("d")
def analyze_d(repo_root: Path) -> AnalysisResult:
    """Analyze D language files in a repository.

    Uses two-pass analysis:
    - Pass 1: Extract all symbols from all files
    - Pass 2: Extract edges (imports + calls) using NameResolver

    Returns a AnalysisResult with symbols for modules, functions, structs,
    classes, and interfaces, plus edges for imports and calls.
    """
    return _analyzer.analyze(repo_root)
