# SPDX-License-Identifier: AGPL-3.0-or-later
"""Tests for scripts/refresh-stdlib-modules (F3 PR-C).

Covers:
- Version mismatch (running interpreter vs --version): error path
- YAML-vs-CLI version mismatch: error path
- Determinism: same script + same interpreter → byte-identical output
- Unsupported language: error path with "not yet implemented" message
- Missing --version for python: error path
- Initial population (first-time insert with no existing block): inserts
  sentinel-delimited block at end of file.
"""
from __future__ import annotations

import importlib.machinery
import importlib.util
import subprocess
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPT_PATH = REPO_ROOT / "scripts" / "refresh-stdlib-modules"


def _load_script_module():
    """Load the script as a Python module without executing CLI."""
    loader = importlib.machinery.SourceFileLoader(
        "refresh_stdlib_modules_under_test",
        str(SCRIPT_PATH),
    )
    spec = importlib.util.spec_from_loader(loader.name, loader)
    mod = importlib.util.module_from_spec(spec)
    loader.exec_module(mod)
    return mod


def _run_script(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, str(SCRIPT_PATH), *args],
        capture_output=True,
        text=True,
        check=False,
    )


def test_unsupported_language_errors(tmp_path: Path) -> None:
    """Unknown language argument exits non-zero with explanatory message."""
    result = _run_script("ocaml", "--version", "5.1")
    assert result.returncode == 1
    assert "not yet implemented" in result.stderr


def test_python_requires_version_flag() -> None:
    """``python`` without --version errors out."""
    result = _run_script("python")
    assert result.returncode == 1
    assert "--version" in result.stderr


def test_python_version_mismatch_with_interpreter(tmp_path: Path) -> None:
    """--version that doesn't match sys.version_info[:2] errors out."""
    bogus = "9.99"
    result = _run_script("python", "--version", bogus)
    assert result.returncode == 1
    assert bogus in result.stderr


def test_python_version_mismatch_with_yaml(tmp_path: Path) -> None:
    """--version that doesn't match YAML's stdlib_provenance.version errors out.

    Drives the script against an isolated YAML fixture so it cannot
    affect the shipped catalog.
    """
    mod = _load_script_module()
    interp_version = f"{sys.version_info[0]}.{sys.version_info[1]}"
    # YAML declares a DIFFERENT version than the running interpreter.
    other_version = (
        f"{sys.version_info[0]}.{sys.version_info[1] + 100}"
    )
    yaml_path = tmp_path / "python.yaml"
    yaml_path.write_text(
        "language: python\n"
        "status: complete\n"
        "stdlib_provenance:\n"
        "  source_url: https://docs.python.org/x/library/index.html\n"
        f'  version: "{other_version}"\n'
        '  retrieved: "2024-01-01"\n',
        encoding="utf-8",
    )
    # Call the refresh function directly with the YAML's declared version.
    # The interpreter check catches the mismatch first; the second branch
    # is exercised when we lie about the interpreter version, so call
    # with interp_version which matches the interpreter — then the YAML
    # mismatch is what trips it.
    rc = mod._refresh_python(yaml_path, interp_version)
    assert rc == 1


def test_python_first_time_insert(tmp_path: Path) -> None:
    """When the YAML has no existing stdlib_modules block, the script
    appends a sentinel-delimited block and updates the retrieved date.
    """
    mod = _load_script_module()
    interp_version = f"{sys.version_info[0]}.{sys.version_info[1]}"
    yaml_path = tmp_path / "python.yaml"
    yaml_path.write_text(
        "language: python\n"
        "status: complete\n"
        "stdlib_provenance:\n"
        "  source_url: https://docs.python.org/3/library/index.html\n"
        f'  version: "{interp_version}"\n'
        '  retrieved: "2024-01-01"\n',
        encoding="utf-8",
    )
    rc = mod._refresh_python(yaml_path, interp_version)
    assert rc == 0
    text = yaml_path.read_text(encoding="utf-8")
    assert "stdlib_modules:" in text
    assert (
        "# BEGIN generated by scripts/refresh-stdlib-modules python"
        in text
    )
    assert "# END generated" in text
    # ``os`` must be in the regenerated list.
    assert "\n  - os\n" in text
    # ``retrieved`` was bumped off the stale 2024 date.
    assert '"2024-01-01"' not in text


def test_python_determinism(tmp_path: Path) -> None:
    """Same script + same interpreter → byte-identical YAML after two runs.

    Plan calls this out explicitly; protects against silent set/dict
    iteration-order drift (e.g., from frozenset(sys.stdlib_module_names)
    being iterated without sorting somewhere).
    """
    mod = _load_script_module()
    interp_version = f"{sys.version_info[0]}.{sys.version_info[1]}"
    yaml_path = tmp_path / "python.yaml"
    yaml_path.write_text(
        "language: python\n"
        "status: complete\n"
        "stdlib_provenance:\n"
        "  source_url: https://docs.python.org/3/library/index.html\n"
        f'  version: "{interp_version}"\n'
        '  retrieved: "2024-01-01"\n',
        encoding="utf-8",
    )
    # First run populates.
    rc = mod._refresh_python(yaml_path, interp_version)
    assert rc == 0
    first = yaml_path.read_text(encoding="utf-8")
    # Second run on already-populated YAML — block replace path.
    rc = mod._refresh_python(yaml_path, interp_version)
    assert rc == 0
    second = yaml_path.read_text(encoding="utf-8")
    assert first == second, (
        "refresh-stdlib-modules is not deterministic: same script + same "
        "interpreter produced different YAML on second run."
    )


def test_python_no_provenance_version_errors(tmp_path: Path) -> None:
    """YAML missing stdlib_provenance.version is an explicit error."""
    mod = _load_script_module()
    interp_version = f"{sys.version_info[0]}.{sys.version_info[1]}"
    yaml_path = tmp_path / "python.yaml"
    yaml_path.write_text(
        "language: python\n"
        "status: complete\n",
        encoding="utf-8",
    )
    rc = mod._refresh_python(yaml_path, interp_version)
    assert rc == 1


def test_main_python_missing_yaml_errors(tmp_path: Path, monkeypatch) -> None:
    """When python.yaml is missing the script reports and exits 1."""
    mod = _load_script_module()
    # Point CATALOG_DIR at an empty tmp_path so the python.yaml lookup misses.
    monkeypatch.setattr(mod, "CATALOG_DIR", tmp_path)
    monkeypatch.setattr(
        sys, "argv", ["refresh-stdlib-modules", "python", "--version", "3.12"],
    )
    rc = mod.main()
    assert rc == 1
