# SPDX-License-Identifier: AGPL-3.0-or-later
"""Consumer-side helper for reading hypergumbo behavior maps (WI-mokim).

Symmetric counterpart to ``safety_zones.user_out_open_json_dump_gzip``,
which is the producer for ``hypergumbo run --gzip``. The producer
writes ``.json`` or ``.json.gz`` purely on path-suffix routing; this
loader uses the same path-suffix rule rather than magic-byte sniffing
so behavior is identical to ``json.loads(path.read_text())`` for plain
files and only diverges when the caller explicitly hands over a
``.gz`` path.

Centralizes the read path so every CLI subcommand and bakeoff/analysis
script that consumes ``--input`` honors ``--gzip`` outputs without each
caller rolling its own suffix check. Prior to WI-mokim only
``scripts/bakeoff-deep`` was wired up (via its own
``_find_hg_json``/``_open_hg_json`` helpers), and feeding a ``.gz``
behavior map into any other consumer dumped gzip bytes into
``json.loads`` and exploded.
"""

from __future__ import annotations

import gzip
import json
import sys
from pathlib import Path
from typing import Any, Dict, Optional, Union

from .schema import SCHEMA_VERSION


class SubstrateError(Exception):
    """A ``--input`` substrate could not be loaded as a usable behavior map.

    Raised by :func:`load_substrate` when the input is not parseable JSON,
    is not a top-level object, lacks the structural ``nodes`` key, or
    carries the wrong ``view`` discriminator. The CLI's top-level dispatch
    (``cli.main``) catches this and converts it to a clean ``rc=2`` +
    stderr message, so every ``--input`` consumer gets a typed failure
    instead of a raw traceback (INV-sozop) or a silent ``rc=0`` "No X
    found" on wrong-shape input (WI-jukah).
    """


# The one structural key whose absence makes a dict indistinguishable from
# "an empty behavior map" to a consumer doing ``data.get("nodes", [])`` — the
# WI-jukah silent-empty root cause. ``schema_version`` is deliberately NOT in
# this reject-set: WI-marul governs it as a warn-first signal (see
# ``load_substrate``), so an absent/mismatched version warns rather than
# rejecting (a map generated by an older build is still usable).
_REQUIRED_SUBSTRATE_KEYS = ("nodes",)


def load_substrate(
    path: Union[Path, str], *, expected_view: str = "behavior_map"
) -> Dict[str, Any]:
    """Strictly load a behavior-map substrate for a ``--input`` consumer.

    The hardened counterpart to :func:`load_behavior_map` (which stays
    permissive for auxiliary artifacts). Four guards, one per member of the
    substrate-loader keystone bundle:

    - **INV-sozop (parse):** a ``json.JSONDecodeError`` (malformed or empty
      file) or a non-object root raises :class:`SubstrateError` instead of
      escaping as an unhandled traceback.
    - **WI-jukah (shape):** a dict lacking the structural ``nodes`` key is
      not a behavior map — reject it rather than let the consumer silently
      emit empty output.
    - **INV-gapib (view discriminator):** a document whose ``view`` field is
      *present and different* from ``expected_view`` (e.g. a ``slice`` or
      ``compact`` projection fed to a behavior-map consumer) is rejected. A
      *missing* ``view`` is accepted — legacy/minimal maps omit it, and the
      concern is a *wrong* view, not an absent one.
    - **WI-marul (schema_version):** an absent or mismatched
      ``schema_version`` **warns** to stderr (warn-first) but still loads —
      a map from an older/newer build is usually still readable, and
      rejecting it would be over-strict.

    Returns the parsed behavior-map dict. Propagates ``FileNotFoundError``
    for a genuinely missing path (consumers check existence and print their
    own message before calling this).
    """
    try:
        data = load_behavior_map(path)
    except json.JSONDecodeError as exc:
        raise SubstrateError(
            f"{path}: not valid JSON ({exc})"
        ) from exc
    if not isinstance(data, dict):
        raise SubstrateError(
            f"{path}: expected a JSON object at the top level, got "
            f"{type(data).__name__}"
        )
    missing = [k for k in _REQUIRED_SUBSTRATE_KEYS if k not in data]
    if missing:
        raise SubstrateError(
            f"{path}: not a hypergumbo behavior map — missing required "
            f"key(s): {', '.join(missing)}"
        )
    view = data.get("view")
    if view is not None and view != expected_view:
        raise SubstrateError(
            f"{path}: wrong view — expected '{expected_view}', got "
            f"'{view}'. Feed a '{expected_view}' behavior map, not a "
            f"'{view}' projection."
        )
    sv = data.get("schema_version")
    if sv is None:
        print(
            f"Warning: {path}: no schema_version field; cannot verify "
            f"substrate compatibility with this build ('{SCHEMA_VERSION}').",
            file=sys.stderr,
        )
    elif sv != SCHEMA_VERSION:
        print(
            f"Warning: {path}: substrate schema_version '{sv}' differs from "
            f"this build's '{SCHEMA_VERSION}'; field presence may not match.",
            file=sys.stderr,
        )
    return data


def load_behavior_map(path: Union[Path, str]) -> Any:
    """Read a hypergumbo behavior map from ``path``, decompressing on demand.

    Routes on the lowercase ``.gz`` suffix to match the producer side
    (``cli.cmd_run --gzip``), which only ever writes lowercase ``.gz``.
    Returns the parsed JSON content (typically a ``dict`` for the main
    behavior map, but the type signature stays open so the helper can
    also load auxiliary JSON-shaped artifacts like compact outputs that
    share the same on-disk convention).

    Raises ``FileNotFoundError`` (from the underlying open) if the path
    is missing; the caller is responsible for the user-facing message.
    """
    p = Path(path)
    if str(p).endswith(".gz"):
        with gzip.open(p, "rt") as f:
            return json.load(f)
    with open(p) as f:
        return json.load(f)


def find_behavior_map(directory: Union[Path, str], basename: str = "hg.json") -> Optional[Path]:
    """Locate a behavior map inside ``directory`` by basename.

    Returns the path to ``<directory>/<basename>`` if it exists, falling
    back to the ``.gz`` variant. Plain JSON wins ties (mirrors the
    bakeoff-deep ``_find_hg_json`` convention and ADR-equivalent
    expectation that an uncompressed file present alongside a compressed
    one is the freshly-written copy). Returns ``None`` if neither
    exists.

    Used by bakeoff scripts and ``analyze-artifacts`` to discover
    hypergumbo outputs without each caller hardcoding the ``hg.json``
    basename twice (once plain, once ``.gz``).
    """
    d = Path(directory)
    plain = d / basename
    if plain.exists():
        return plain
    gz = d / (basename + ".gz")
    if gz.exists():
        return gz
    return None
