# SPDX-License-Identifier: AGPL-3.0-or-later
"""Render ``docs/CATALOGUES.md``: the one user-facing page about catalogue data.

ADR-0061 ruling 6: user-facing text names four tiers -- built-in, community,
yours, in-repo -- and one page, ``docs/CATALOGUES.md``, says what they are,
where each family's files live, how to add a row to each family, and what each
tier can do to a verdict.

THE REGISTRY FACTS ARE GENERATED, NOT WRITTEN. The family list, each family's
channel, whether the channel is read, its section scope and its gate, and the
built-in / community file counts all come from
:data:`hypergumbo_core.yaml_catalogs.YAML_CATALOGS`, the wired-channel set and
the files' own ``provenance:`` lines. A page that restated them by hand would
drift the day a family gained a channel -- the shape ADR-0047 ruling 3 was
filed about. ``scripts/generate-catalogues-doc`` writes the page and
``test_catalogues_doc.py`` fails when the committed page differs from what this
module renders.

THE PROSE THAT CANNOT BE DERIVED IS KEYED BY FAMILY. What a family is for comes
from :data:`catalogue_inventory.FAMILY_CONSEQUENCE`; how to add a row is
:data:`HOW_TO_ADD`, one example per extensible family. A test asserts both
cover every family the registry declares, so a new family cannot reach this
page with a blank answer.
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional

import yaml

from .catalogue_home import WIRED_CHANNELS
from .catalogue_inventory import FAMILY_CONSEQUENCE
from .yaml_catalogs import PROVENANCE_COMMUNITY, YAML_CATALOGS, CatalogSpec

_PKG_ROOT = Path(__file__).parent

#: One minimal row per extensible family, as it would appear in the file you
#: drop in the family's channel. Kept short on purpose: the page teaches the
#: SHAPE, and each family's own shipped files and ADR carry the full schema.
HOW_TO_ADD: dict[str, str] = {
    "io_primitives": (
        "language: python\n"
        "status: overlay\n"
        "retrieved: 2026-09-30        # when you last checked the library\n"
        "net_send:\n"
        "  - module: inhouse_http\n"
        "    functions: [post]"
    ),
    "frameworks": (
        "# frameworks.d/<framework id>.yaml REPLACES the shipped definition of\n"
        "# that framework whole (a definition is one coherent convention).\n"
        "id: inhouse_web\n"
        "language: python\n"
        "patterns:\n"
        "  - concept: route\n"
        "    decorator: \"^app\\\\.route$\"\n"
        "    extract_path: \"args[0]\""
    ),
    "dataflow_patterns": (
        "# dataflow_patterns.d/<language>.yaml -- only library_patterns is read\n"
        "language: python\n"
        "library_patterns:\n"
        "  - match: '\\.enqueue\\('\n"
        "    access_mode: write"
    ),
    "function_summaries": (
        "summaries:\n"
        "  - function: \"inhouse_log.record\"\n"
        "    param_to_return: {}\n"
        "    side_effect: true      # TERMINATING: rides the user-supplied caveat"
    ),
    "library_signatures": (
        "# library_signatures.d/<language>.yaml\n"
        "language: go\n"
        "signatures:\n"
        "  inhouse.Open: inhouse.Handle"
    ),
    "taint_sources": (
        "taint_label: pii\n"
        "sources:\n"
        "  python:\n"
        "    - module: crm\n"
        "      functions: [lookup]"
    ),
    "taint_sinks": (
        "zone: audit_log\n"
        "trust_level: untrusted\n"
        "sinks:\n"
        "  python:\n"
        "    - module: audit\n"
        "      functions: [record]"
    ),
    "taint_sanitizers": (
        "transforms:\n"
        "  - input_taint: pii\n"
        "    output_taint: redacted\n"
        "    functions:\n"
        "      python:\n"
        "        - crm.redact       # rides the user-supplied-sanitizer caveat"
    ),
}


def _tier_counts(directory: Path) -> tuple[int, int]:
    """``(built-in, community)`` files, read from each file's own line."""
    builtin = community = 0
    for path in sorted(directory.glob("*.yaml")):
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        if data.get("provenance") == PROVENANCE_COMMUNITY:
            community += 1
        else:
            builtin += 1
    return builtin, community


def _channel_cell(spec: CatalogSpec) -> str:
    channel = spec.user_channel
    if channel is None:
        return "none"
    cell = f"`{channel}/`"
    if channel not in WIRED_CHANNELS:
        cell += " (declared, NOT read yet)"
    if spec.channel_scope:
        cell += f", `{spec.channel_scope}` only"
    if spec.channel_gated:
        cell += ", rides the user-supplied caveat"
    return cell


_INTRO = """\
<!-- SPDX-License-Identifier: AGPL-3.0-or-later -->
# Catalogues

<!-- GENERATED by scripts/generate-catalogues-doc from
     hypergumbo_core.yaml_catalogs; edit catalogues_doc.py, not this file. -->

hypergumbo's analyses run on **catalogues**: YAML rows that say which calls
are I/O, which values are tainted, what makes them safe, what a library
returns, how a framework dispatches. This page says whose word each row is,
what that lets it do to a verdict, and how to add your own
([ADR-0061](adr/0061-catalogue-tiers-for-every-family.md)).

## The four tiers

| tier | what | vouched for by | where it lives | can it make a verdict cleaner? |
|---|---|---|---|---|
| **built-in** | standard-library and platform rows | hypergumbo | the installed package, `provenance: builtin` | yes |
| **community** | third-party library rows, shipped but not maintained, dated by `retrieved:` | nobody | the installed package, `provenance: community` | no: it can add a finding, never remove one or an uncertainty |
| **yours** | rows you supply | you | `$XDG_CONFIG_HOME/hypergumbo/` (`config.toml`, one `<family>.d/` per family below), or a file you name on the command line | yes, and a clean verdict that relied on your sanitizer or terminating summary says so (exit 3) |
| **in-repo** | catalogue data inside the analysed repository that you did not name | nobody, until you opt in | the catalogue keys of `<repo>/.hypergumbo.toml` | only after you opt in |

A row makes a verdict *cleaner* when it can move it toward `confirmed`: a
sanitizer, a summary that ends a taint branch, a `module_completeness` grant,
an I/O row that makes a call count as examined, a library signature that
types a receiver. A source, a sink, a framework pattern or an I/O detection
only ever adds.

**A file's tier is its own `provenance:` line**, never the directory it sits
in. A community file you copy into your config home is still community;
deleting its `provenance: community` line is how you vouch for it, and it is
then yours.
"""

_OUTRO = """\
## Opting in to a repository's own catalogue data

A repository's `.hypergumbo.toml` may set preferences (`[merge]`, `[backends]`),
and those load by default. Its **catalogue** keys (today `io_primitives`) load
only when you opt in:

- for one run: `--in-repo-catalogues` (`io-boundaries`, `verify-claims`);
- for one repository: `hypergumbo trust-catalogues [PATH]`, recorded under
  `$XDG_STATE_HOME/hypergumbo/` and keyed by the resolved path
  (`--revoke` records a refusal, `--show` prints the decision).

A file you name on the command line (`--claims`, `--io-primitives`,
`--taint-*`) is opted in by naming it. Until you decide, a run that skips
in-repo catalogue data says which files it did not load.

## Turning community rows off

`--no-default-overlays` omits community rows from the verify step: the
shipped community I/O overlays, every overlay declaring
`provenance: community`, the taint sinks and sources derived from them, and
the community taint and function-summary files. It does not reach the
analysis that builds the graph.

## Seeing what a run rested on

- `verify-claims --format json` lists every catalogue file the run read under
  `catalog_provenance.tiers` (`builtin` / `community` / `yours` / `in_repo`,
  with git state `committed` / `modified` / `untracked` for a file inside the
  repository), names every `module_completeness` grant and where it came from,
  and lists a community file's withheld grants separately.
- `hypergumbo catalog-inventory` shows each family, its file count, your
  channel and whether it is read.
- `hypergumbo init-catalogs` creates your catalogue home and seeds the
  community I/O overlays into `io_primitives.d/` so you can edit them.
"""


def render_catalogues_markdown(pkg_root: Optional[Path] = None) -> str:
    """The whole of ``docs/CATALOGUES.md``."""
    root = pkg_root if pkg_root is not None else _PKG_ROOT
    out = [_INTRO, "## Every family\n",
           "| family | built-in files | community files | your channel | what it is for |",
           "|---|---|---|---|---|"]
    for spec in YAML_CATALOGS:
        builtin, community = _tier_counts(root / spec.directory)
        out.append(
            f"| `{spec.directory}` | {builtin} | {community} | "
            f"{_channel_cell(spec)} | {FAMILY_CONSEQUENCE[spec.directory]} |"
        )
    out.append("")
    out.append("Families with no channel say why in the registry: their rows "
               "describe grammar node types or hypergumbo's own engines "
               "(`cfg_nodes`, `url_folding`), or they have a home already "
               "(`io_primitives_overlays` rows are overridden from "
               "`io_primitives.d/`).\n")
    out.append("## Adding your own rows\n")
    out.append("Drop a YAML file in the family's channel under "
               "`$XDG_CONFIG_HOME/hypergumbo/`. A minimal row for each:\n")
    for spec in YAML_CATALOGS:
        if spec.user_channel is None:
            continue
        out.append(f"### `{spec.user_channel}/` ({spec.directory})\n")
        out.append("```yaml")
        out.append(HOW_TO_ADD[spec.directory])
        out.append("```\n")
    out.append(_OUTRO)
    return "\n".join(out)
