# SPDX-License-Identifier: AGPL-3.0-or-later
"""File discovery: excludes, installed-dependency detection, locales, ambiguous extensions.

Provides shared utilities for finding source files across the repository while
respecting exclude patterns. Also provides:

- **Locale-aware doc filtering:** ``detect_locale_dirs()`` identifies translated
  documentation directories (GitLab-style ``doc-locale/<lang>/`` and FastAPI-style
  ``docs/<lang>/``). By default, translated docs are excluded to avoid processing
  duplicate content. The ``--locale`` CLI flag swaps to a specific locale instead.
  ``set_locale_excludes()`` / ``get_locale_excludes()`` provide a global hook
  (like ``set_max_file_bytes``) that ``find_files`` checks.

- **Single-walk file index:** ``set_file_index()`` installs a global
  ``FileIndex`` that REPLACES ``find_files``' source of files: whenever the
  installed index's ``repo_root`` equals the requested one, ``find_files``
  matches patterns against the index (applying only ``max_files`` and the
  size limit -- the ``excludes`` argument is not re-checked) and never walks
  the tree. ``cli.run_survey`` installs one built from a single ``os.walk``
  (``FileIndex.build``) and clears it on every exit path; ``sketch`` installs
  a map-scoped ``FileIndex.from_paths`` for the ``--input`` / warm-map case
  (INV-jumim), so ``find_files`` then yields only the map's files. With no
  index installed, ``find_files`` falls back to ``rglob`` per pattern.

- **Ambiguous extension disambiguation:**

  - ``.m`` files: shared by Objective-C, MATLAB, and Wolfram.
    ``classify_dot_m_file`` reads file content and uses syntactic heuristics.
  - ``.d`` files: shared by D programming language and GCC Makefile dependency
    files (generated by ``gcc -MMD``). ``classify_dot_d_file`` distinguishes
    D source from dependency files by checking for D keywords vs make rules.

- **Content-conditioned virtualenv exclusion:** ``venv`` / ``.venv`` / ``env``
  are deliberately NOT in ``DEFAULT_EXCLUDES``. A directory is a virtualenv
  because of what it CONTAINS, not what it is called — ``env/`` is just as
  often an application's config or environment package, and name-matching it
  silently deleted real source from the analysis. ``VENV_DIR_NAMES`` selects
  which names are even eligible for the test; ``_looks_like_virtualenv`` then
  requires one of ``_VENV_MARKERS`` (``pyvenv.cfg`` — PEP 405's specified
  marker — or ``bin/activate`` / ``Scripts/activate`` for older and Windows
  tooling) at the directory root. Disclosed limit: the Windows arm has no
  real-world positive control (zero hits across the 467-repo corpus), so it
  is asserted by fixture only and is not claimed to be validated.

- **Installed dependency source, recognised by content (ADR-0004
  §"Installed dependency source").** The virtualenv rule generalised to every
  ecosystem: ``INSTALLED_DEP_RULES`` is a registry of
  ``ContentRule(dir_name, ecosystem, marker, packages)`` entries — Mix
  ``deps/``, ``node_modules/``, Composer and Go ``vendor/``, Bundler
  ``vendor/bundle``, CocoaPods ``Pods/``, virtualenvs. The name only selects
  which directories get the marker test (one set lookup, so every other
  directory costs nothing); the marker decides; and a directory whose files
  are COMMITTED (present in HEAD, ``_is_committed_dir``) is vendored code,
  never installed, whatever marker it carries. ``match_content_rule`` is the
  single test. Installed source is pruned unless ``--trace-deps`` / the
  ``trace_deps`` config key opts in — wholesale (``all``) or per package, in
  which case ``content_rule_prunes`` keeps only the traced packages' paths
  inside the directory (and the directories on the way to them). The policy
  the walk applies lives in process state set by ``cli.run_survey``
  (``set_active_trace_deps``), like the file index, because the walkers are
  reached from every analyzer without a parameter path; the flag's value is
  recorded by ``cli.main`` (``set_trace_deps_override``) and
  ``resolve_trace_deps`` is the one place flag, config and default are
  combined, read by both the walk and the results-cache key.
  ``BUILD_OUTPUT_RULES`` uses the same shape for tool output whose name is
  too generic to exclude outright (Mix ``cover/``, Phoenix
  ``priv/static/assets``, ``.dart_tool``, ``.stack-work``, ``elm-stuff``):
  always pruned, no opt-in, not disclosed. ``FileIndex.build`` records every
  installed directory it meets (``installed_dep_roots``);
  ``installed_deps_summary`` / ``format_installed_deps_disclosure`` turn
  those into ``supply_chain_summary.installed_deps_skipped`` and the
  one-line stderr/sketch disclosure. Hand-written project-manifest walks
  (``walks_into`` + ``manifest_walk_skip``) never enter a content-claimed
  directory, traced or not, and keep skipping ``node_modules`` / ``vendor``
  by name: a dependency's manifest never names the project.
"""
from __future__ import annotations

import functools
import re
from dataclasses import dataclass, field
from fnmatch import fnmatch
from pathlib import Path
from typing import Any, Callable, Iterable, Iterator

from .paths import is_test_file

# Global file size limit. Set via set_max_file_bytes() before running
# analyzers; find_files() reads this when no explicit max_file_bytes
# is passed. Reset to None after use.
_global_max_file_bytes: int | None = None

# Global callback for skipped files. Set via set_global_on_file_skipped()
# before running analyzers; find_files() uses this when no explicit
# on_file_skipped callback is provided. This allows run_all_analyzers()
# to collect truncated file info without modifying any analyzer signatures.
_global_on_file_skipped: Callable[[Path, int, str], None] | None = None


def set_max_file_bytes(limit: int | None) -> None:
    """Set the global max file bytes limit for find_files().

    Called by the CLI before running analyzers so that all callers of
    find_files() respect the limit without needing individual changes.
    """
    global _global_max_file_bytes
    _global_max_file_bytes = limit


def set_global_on_file_skipped(
    callback: Callable[[Path, int, str], None] | None,
) -> None:
    """Set a global callback for files skipped due to size limits.

    Called by run_all_analyzers() to wire skipped-file tracking into
    the Limits object without modifying individual analyzer signatures.
    When find_files() skips a file and no explicit on_file_skipped
    callback is provided, it falls back to this global callback.
    """
    global _global_on_file_skipped
    _global_on_file_skipped = callback


# ---------------------------------------------------------------------------
# Locale-aware documentation directory handling
# ---------------------------------------------------------------------------

# Global list of absolute directory paths to exclude for locale filtering.
# Set via set_locale_excludes() before running analyzers; find_files() reads
# this to skip translated documentation directories.
_global_locale_excludes: list[Path] | None = None

# ISO 639-1 two-letter codes and common locale tags used as directory names.
# Used to distinguish docs/en/, docs/ja/ from docs/api/, docs/guide/.
_LOCALE_CODES = frozenset({
    # Common ISO 639-1 codes seen in real repos
    "af", "am", "ar", "az", "be", "bg", "bn", "bs", "ca", "cs", "cy", "da",
    "de", "el", "en", "es", "et", "eu", "fa", "fi", "fil", "fr", "ga", "gl",
    "gu", "ha", "he", "hi", "hr", "hu", "hy", "id", "ig", "is", "it", "ja",
    "jv", "ka", "kk", "km", "kn", "ko", "ku", "ky", "lb", "lo", "lt", "lv",
    "mg", "mi", "mk", "ml", "mn", "mr", "ms", "mt", "my", "nb", "ne", "nl",
    "nn", "no", "ny", "or", "pa", "pl", "ps", "pt", "ro", "ru", "rw", "sd",
    "si", "sk", "sl", "sn", "so", "sq", "sr", "st", "su", "sv", "sw", "ta",
    "te", "tg", "th", "tk", "tl", "tn", "tr", "ts", "tt", "ug", "uk", "ur",
    "uz", "vi", "wo", "xh", "yi", "yo", "zh", "zu",
})

# Extended locale tags: "xx-yy" patterns like "ja-jp", "pt-br", "zh-hans"
_LOCALE_TAG_PATTERN = re.compile(
    r"^[a-z]{2}(?:-[a-z]{2,4})?$",  # e.g. "ja", "ja-jp", "zh-hans"
)


def _is_locale_dirname(name: str) -> bool:
    """Check if a directory name looks like a locale/language code.

    Matches ISO 639-1 two-letter codes (en, ja, fr) and extended tags
    (ja-jp, pt-br, zh-hans). Rejects common non-locale directory names
    like 'api', 'guide', 'images'.
    """
    lower = name.lower()
    if lower in _LOCALE_CODES:
        return True
    return bool(_LOCALE_TAG_PATTERN.match(lower))


@dataclass
class LocaleInfo:
    """Information about detected locale documentation directories.

    Attributes:
        style: Either "doc-locale" (GitLab-style) or "docs-peer" (FastAPI-style).
        repo_root: The repository root path.
        primary_dir: Path to the primary/English documentation directory.
        languages: List of non-primary language codes found.
        locale_dirs: Mapping from language code to its directory path.
    """

    style: str
    repo_root: Path
    primary_dir: Path
    languages: list[str]
    locale_dirs: dict[str, Path] = field(default_factory=dict)

    def excludes_for_locale(self, locale: str | None) -> list[Path]:
        """Compute which directories to exclude given a --locale value.

        Args:
            locale: None for default (exclude translations, keep primary),
                or a language code to swap to that locale.

        Returns:
            List of absolute directory paths to exclude.

        Raises:
            ValueError: If the requested locale doesn't exist.
        """
        if locale is None:
            # Default: exclude all translation dirs, keep primary
            return list(self.locale_dirs.values())

        if locale not in self.locale_dirs:
            available = sorted(self.locale_dirs.keys())
            raise ValueError(
                f"Locale '{locale}' not found. "
                f"Available locales: {', '.join(available)}"
            )

        # Swap: exclude primary + all other locales, keep requested
        excludes = [self.primary_dir]
        for lang, d in self.locale_dirs.items():
            if lang != locale:
                excludes.append(d)
        return excludes


def detect_locale_dirs(repo_root: Path) -> LocaleInfo | None:
    """Detect translated documentation directories in a repository.

    Recognizes two patterns:

    1. **GitLab-style** (``doc-locale/<lang>/``): English docs live in ``doc/``,
       translations live in ``doc-locale/<lang>/``. Detected when ``doc-locale/``
       exists and contains subdirectories with locale-like names.

    2. **FastAPI-style** (``docs/<lang>/``): All languages are peer directories
       under ``docs/``, including ``docs/en/``. Detected when ``docs/`` contains
       ``en/`` plus other locale-named directories.

    Args:
        repo_root: Repository root path.

    Returns:
        LocaleInfo if locale directories are found, None otherwise.
    """
    # Pattern 1: GitLab-style doc-locale/<lang>/
    doc_locale = repo_root / "doc-locale"
    if doc_locale.is_dir():
        langs: dict[str, Path] = {}
        for child in sorted(doc_locale.iterdir()):
            if child.is_dir() and _is_locale_dirname(child.name):
                langs[child.name.lower()] = child
        if langs:
            # Primary is doc/ (English)
            primary = repo_root / "doc"
            if not primary.is_dir():
                primary = repo_root / "docs"
            return LocaleInfo(
                style="doc-locale",
                repo_root=repo_root,
                primary_dir=primary,
                languages=sorted(langs.keys()),
                locale_dirs=langs,
            )

    # Pattern 2: FastAPI-style docs/<lang>/
    docs_dir = repo_root / "docs"
    if docs_dir.is_dir():
        en_dir = docs_dir / "en"
        if en_dir.is_dir():
            langs = {}
            for child in sorted(docs_dir.iterdir()):
                if child.is_dir() and child.name.lower() != "en" and _is_locale_dirname(child.name):
                    langs[child.name.lower()] = child
            if langs:
                return LocaleInfo(
                    style="docs-peer",
                    repo_root=repo_root,
                    primary_dir=en_dir,
                    languages=sorted(langs.keys()),
                    locale_dirs=langs,
                )

    return None


def set_locale_excludes(excludes: list[Path] | None) -> None:
    """Set the global locale directory excludes for find_files().

    Called by the CLI after detect_locale_dirs() to wire locale filtering
    into all analyzers without modifying their signatures.

    Args:
        excludes: List of absolute directory paths to exclude, or None
            to disable locale filtering.
    """
    global _global_locale_excludes
    _global_locale_excludes = excludes


def get_locale_excludes() -> list[Path] | None:
    """Get the current global locale directory excludes.

    Returns:
        The list set by set_locale_excludes(), or None if not set.
    """
    return _global_locale_excludes


def _is_under_locale_exclude(path: Path) -> bool:
    """Check if a path falls under any of the global locale exclude dirs.

    Uses Path.is_relative_to() for efficient prefix matching.
    """
    if _global_locale_excludes is None:
        return False
    for exclude_dir in _global_locale_excludes:
        try:
            if path.is_relative_to(exclude_dir):
                return True
        except (TypeError, ValueError):  # pragma: no cover
            continue
    return False


# Compiled patterns for .m file disambiguation — compiled once at import time.
# Objective-C: preprocessor directives and @-keywords
_OBJC_PATTERNS = re.compile(
    r"(?:^#import\b|^#include\b|^@interface\b|^@implementation\b"
    r"|^@protocol\b|^@end\b|^@property\b|^@synthesize\b|^@dynamic\b"
    r"|^#pragma\b)",
    re.MULTILINE,
)
# Wolfram: pattern-match arguments (x_), scoping constructs, package structure
_WOLFRAM_PATTERNS = re.compile(
    r"(?:\w+\[[\w_,\s]*\w+_[\w]*\]\s*:="  # f[x_] := or f[x_, y_Integer] :=
    r"|(?:Module|Block|With)\["            # scoping constructs
    r"|BeginPackage\[|EndPackage\["         # package structure
    r"|Needs\[|Get\["                       # imports
    r"|\(\*)",                              # block comments (* ... *)
    re.MULTILINE,
)
# MATLAB: function/classdef keywords at start of line
_MATLAB_PATTERNS = re.compile(
    r"(?:^function\b|^classdef\b)",
    re.MULTILINE,
)

# D language: keywords and attributes distinctive to D source code
_D_SOURCE_PATTERNS = re.compile(
    r"(?:^module\s+\w|^import\s+\w"       # module/import declarations
    r"|^(?:class|struct|interface|enum)\s"  # type definitions
    r"|^unittest\b"                         # unittest blocks
    r"|@(?:safe|trusted|nogc|system)\b"     # D-specific attributes
    r"|\bvoid\s+\w+\s*\("                  # void function defs
    r"|\bauto\s+\w+\s*=)",                 # auto variable defs
    re.MULTILINE,
)

# GCC dependency file: target.o: prerequisite.c header.h
# First line typically matches this pattern; we check only the first line
# to avoid false matches inside D source comments.
_GCC_DEP_PATTERN = re.compile(
    r"^\S+\.o\s*:\s*\S+\.\w",
)

# How many bytes to read for classification. 8 KB is enough to capture
# the file header, imports, and first few definitions.
_CLASSIFY_READ_LIMIT = 8192


def classify_dot_m_file(path: Path) -> str:
    """Classify a .m file as 'objc', 'wolfram', or 'matlab'.

    Uses content-based heuristics to disambiguate .m files, which are shared
    by three languages:
    - Objective-C: #import, @interface/@implementation/@protocol, #pragma
    - Wolfram/Mathematica: f[x_] :=, Module[, BeginPackage[, (* comments *)
    - MATLAB: function keyword, classdef keyword, % comments

    Reads the first 8 KB of the file for classification. Returns 'matlab' as
    the default when no strong signals are found (MATLAB is the most common
    user of .m files in practice).

    Args:
        path: Path to a .m file.

    Returns:
        One of 'objc', 'wolfram', or 'matlab'.
    """
    try:
        content = path.read_bytes()[:_CLASSIFY_READ_LIMIT].decode("utf-8", errors="replace")
    except (OSError, PermissionError):
        return "matlab"

    # Check Objective-C first — it has the most distinctive syntax
    if _OBJC_PATTERNS.search(content):
        return "objc"

    # Check Wolfram — pattern-match syntax (x_) is very distinctive
    if _WOLFRAM_PATTERNS.search(content):
        return "wolfram"

    # Check MATLAB keywords
    if _MATLAB_PATTERNS.search(content):
        return "matlab"

    # Default: MATLAB is the most common use of .m files
    return "matlab"


def classify_dot_d_file(path: Path) -> str:
    """Classify a .d file as 'd' (D language source) or 'dependency' (GCC).

    .d files are ambiguous: they can be D programming language source or GCC
    Makefile dependency files generated by ``gcc -MMD``.  Dependency files
    contain make-style ``target.o: prerequisite.c header.h`` rules and should
    not be analyzed as D source.

    .di files (D interface files) are always D source — no ambiguity.

    Reads the first 8 KB of the file for classification.  Returns 'd' as the
    default when no strong signals are found.

    Args:
        path: Path to a .d or .di file.

    Returns:
        One of 'd' or 'dependency'.
    """
    # .di files are always D interface files, no ambiguity
    if path.suffix == ".di":
        return "d"

    try:
        content = path.read_bytes()[:_CLASSIFY_READ_LIMIT].decode(
            "utf-8", errors="replace",
        )
    except (OSError, PermissionError):
        return "d"

    # Check D source patterns first — they are distinctive
    if _D_SOURCE_PATTERNS.search(content):
        return "d"

    # Check GCC dependency file pattern on the first non-empty line
    first_line = ""
    for line in content.split("\n"):
        stripped = line.strip()
        if stripped:
            first_line = stripped
            break
    if first_line and _GCC_DEP_PATTERN.match(first_line):
        return "dependency"

    # Default: assume D source (benefit of the doubt)
    return "d"


# Default exclude patterns (gitignore-style)
DEFAULT_EXCLUDES = [
    # Dependency directories.
    # NOTE: node_modules / vendor / deps / venv / .venv / env / Pods are NOT
    # here. Installed dependency source is recognised by CONTENT, per
    # ecosystem, through INSTALLED_DEP_RULES (ADR-0004 §"Installed dependency
    # source"): a directory is installed dependency source because a package
    # manager filled it, not because of its name -- and a committed
    # (git-tracked) directory is never installed. See match_content_rule.
    ".eggs",
    # Build output
    "dist",
    "build",
    "_build",  # Sphinx docs, Mix
    ".elixir_ls",  # ElixirLS language-server build/cache dir (ADR-0004 §7)
    "out",
    "target",  # Rust, Maven
    # VCS and IDE
    ".git",
    ".svn",
    ".hg",
    # Caches
    "__pycache__",
    ".ipynb_checkpoints",  # Jupyter notebook auto-save copies
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    ".tox",
    ".nox",
    ".cache",
    "*.egg-info",
    ".terraform",  # Terraform providers and modules cache
    # Coverage and test reports
    "htmlcov",  # Python (pytest-cov)
    "coverage",  # Generic (Ruby, JS)
    ".coverage",  # Python coverage.py
    "coverage.xml",  # Python, generic (Cobertura format)
    ".nyc_output",  # JavaScript (nyc/Istanbul)
    "lcov-report",  # JavaScript/C++ (LCOV HTML)
    "lcov.info",  # JavaScript/C++ (LCOV data)
    ".c8_output",  # JavaScript (c8)
    "coverage.out",  # Go
    "cover.out",  # Go (alternate name)
    "cover.html",  # Go (HTML report)
    "tarpaulin-report",  # Rust (cargo-tarpaulin)
    "TestResults",  # .NET (dotnet test)
    "coverlet",  # .NET (Coverlet)
    "gcov-reports",  # C/C++ (gcov)
    "jest-coverage",  # JavaScript (Jest)
    ".jest",  # JavaScript (Jest cache)
    "snapshot_report.html",  # pytest-html snapshot report
    # Documentation output
    "site",  # mkdocs
    "_site",  # Jekyll
    # NOTE: Hugo uses public/ for generated output, but it's typically
    # gitignored.  Excluding "public" caused severe false positives:
    # Airflow routes/public/ (109 API handlers), Laravel/Symfony public/
    # (web root), etc.  Removed in v0.5.1.
    # Hypergumbo output artifacts and agent governance
    ".hypergumbo",
    ".agent",  # Agent tracker ops, hooks, config — not source code
    "survey*.json",  # ADR-0042 canonical: survey.json + survey.<tier>.json side-outputs
    "hypergumbo.results*.json",  # legacy: .json, .4k.json, .16k.json, .64k.json, etc.
    # Lock files - generated, inflate LOC counts
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "poetry.lock",
    "Pipfile.lock",
    "Gemfile.lock",
    "composer.lock",
    "Cargo.lock",
    "go.sum",
    "pubspec.lock",  # Dart/Flutter
    "packages.lock.json",  # NuGet (.NET)
]


#: Directory names that MIGHT be a virtualenv. Membership here is not an exclusion —
#: it only selects which names get the content test in :func:`_looks_like_virtualenv`.
VENV_DIR_NAMES: frozenset[str] = frozenset({"venv", ".venv", "env"})

#: Files whose presence identifies a directory as a virtualenv root. ``pyvenv.cfg`` is
#: PEP 405's specified marker; older tooling wrote only ``bin/activate``, and Windows
#: writes ``Scripts/activate``. The Windows arm has NO real-world positive control —
#: zero hits across the 467-repo corpus and no Windows virtualenv was available — so it
#: is asserted by fixture and is not claimed to be validated.
_VENV_MARKERS: tuple[str, ...] = ("pyvenv.cfg", "bin/activate", "Scripts/activate")


@functools.lru_cache(maxsize=4096)
def _looks_like_virtualenv(directory: str) -> bool:
    """Whether ``directory`` is a virtualenv ROOT, decided by content.

    WHY CONTENT AND NOT NAME. ``venv``/``.venv``/``env`` used to sit in
    :data:`DEFAULT_EXCLUDES` as bare names, and the matcher applies an exact name to
    EVERY component of the relative path at any depth — so every directory named
    ``env`` in every repository was deleted. Measured across 467 corpus repos that is
    **427 source files in 77 directories across 39 repos, 425 of them (99.5%)
    first-party**: RocksDB's entire POSIX I/O layer (``env_posix.cc``, ``fs_posix.cc``,
    ``io_posix.cc``), U-Boot's environment storage subsystem, poetry's virtualenv
    manager. The deleted code is systematically I/O-dense, which is the worst possible
    thing for an exclusion list to remove from a boundary analysis.

    WHY NOT ROOT-ANCHOR IT. ``env/*`` is already expressible in this matcher and needs
    no new machinery, but it recovers only 379 of 427 (88.8%) and **structurally
    cannot** recover the two worst cases — rocksdb's and U-Boot's ``env/`` are both AT
    the repo root, exactly where a virtualenv would be. Only content separates them.
    Conversely a virtualenv is not always at the root (``backend/venv`` is idiomatic),
    so this test stays depth-agnostic.

    DIRECTION: this ADDS analyzable source. It cannot delete a finding. The mirror
    risk — re-including a real virtualenv and dragging in thousands of dependency
    files — is what the markers prevent; this repo's own ``.venv`` (26,882 source
    files) is a live positive control in the test suite.

    This is the Python entry of :data:`INSTALLED_DEP_RULES`; the other ecosystems
    follow the same shape (a candidate name selects the test, content decides).

    Cached because discovery calls this once per candidate directory per walk and the
    answer cannot change within a run. Keyed on ``str`` so the cache is hashable.
    """
    base = Path(directory)
    return any((base / marker).exists() for marker in _VENV_MARKERS)


# ---------------------------------------------------------------------------
# Installed dependency source and tool build output, recognised by content
# (ADR-0004 §"Installed dependency source", points 1-3 and 7)
# ---------------------------------------------------------------------------


def _exists(base: Path, *names: str) -> bool:
    """Every one of ``names`` exists under ``base``."""
    return all((base / n).exists() for n in names)


def _child_dirs(base: Path) -> list[Path]:
    """Sorted real subdirectories of ``base`` (never a symlink -- INV-pivir)."""
    try:
        return sorted(
            c for c in base.iterdir() if c.is_dir() and not c.is_symlink()
        )
    except OSError:  # pragma: no cover - unreadable directory
        return []


def _mix_deps_marker(d: Path) -> bool:
    """Mix ``deps/``: the project's ``mix.exs`` + ``mix.lock`` beside it, or a
    Hex-fetched package inside it (``deps/<pkg>/hex_metadata.config``, written
    by ``mix deps.get`` for every Hex package -- not for git/path deps, which
    is why the sibling arm comes first)."""
    if _exists(d.parent, "mix.exs", "mix.lock"):
        return True
    return any((c / "hex_metadata.config").is_file() for c in _child_dirs(d))


def _mix_deps_packages(d: Path) -> dict[str, Path]:
    """One package per ``deps/<app>/`` directory; the name is the OTP app."""
    return {c.name: c for c in _child_dirs(d) if not c.name.startswith(".")}


#: Package-manager state files npm (>=7), Yarn classic, pnpm and Yarn Berry
#: (``nodeLinker: node-modules``) write at the root of a ``node_modules`` they
#: populated.
_NODE_MODULES_STATE_FILES: tuple[str, ...] = (
    ".package-lock.json", ".yarn-integrity", ".modules.yaml", ".yarn-state.yml",
)


def _node_modules_marker(d: Path) -> bool:
    """``node_modules/``: a ``package.json`` beside it, or a package manager's
    state file inside it.

    WHY THE SIBLING MANIFEST. npm, Yarn and pnpm all install into the
    ``node_modules`` next to the ``package.json`` they resolved, and Node's
    resolver walks up looking for exactly that layout -- so a ``node_modules``
    with a manifest beside it is one a package manager made. That covers nested
    installs too (``node_modules/a/node_modules`` sits beside
    ``node_modules/a/package.json``). The state-file arm covers a tree whose
    manifest has moved away. What is NOT recognised, deliberately: a bare
    ``node_modules`` with neither (resolver test fixtures such as
    ``test/fixtures/node_modules/x/index.js``), which stays analysed; it is
    still classified tier 3 by ``supply_chain``'s ``node_modules/`` pattern.
    Not chosen: "children carry package.json", which needs a listing per
    candidate and is fooled by the same fixtures.
    """
    if (d.parent / "package.json").is_file():
        return True
    return any((d / f).is_file() for f in _NODE_MODULES_STATE_FILES)


def _node_modules_packages(d: Path) -> dict[str, Path]:
    """``node_modules/<pkg>`` and ``node_modules/@scope/<pkg>``; ``.bin`` and
    other dot-entries are tooling, not packages."""
    out: dict[str, Path] = {}
    for c in _child_dirs(d):
        if c.name.startswith("."):
            continue
        if c.name.startswith("@"):
            for s in _child_dirs(c):
                out[f"{c.name}/{s.name}"] = s
        else:
            out[c.name] = c
    return out


def _composer_vendor_marker(d: Path) -> bool:
    """Composer ``vendor/``: ``composer.json`` beside it and the
    ``vendor/autoload.php`` Composer generates on every install."""
    return (d.parent / "composer.json").is_file() and (d / "autoload.php").is_file()


def _composer_vendor_packages(d: Path) -> dict[str, Path]:
    """``vendor/<vendor>/<package>``, named ``vendor/package`` as Composer
    does; ``vendor/bin`` and ``vendor/composer`` are Composer's own."""
    out: dict[str, Path] = {}
    for v in _child_dirs(d):
        if v.name in ("bin", "composer") or v.name.startswith("."):
            continue
        for p in _child_dirs(v):
            out[f"{v.name}/{p.name}"] = p
    return out


def _go_vendor_marker(d: Path) -> bool:
    """Go modules ``vendor/``: ``go.mod`` beside it and the
    ``vendor/modules.txt`` manifest ``go mod vendor`` writes."""
    return (d.parent / "go.mod").is_file() and (d / "modules.txt").is_file()


def _go_vendor_packages(d: Path) -> dict[str, Path]:
    """One package per ``# <module> <version>`` line of ``modules.txt``,
    named by module path, at ``vendor/<module path>``. A line whose directory
    is absent (a module with no vendored packages) names nothing."""
    out: dict[str, Path] = {}
    try:
        text = (d / "modules.txt").read_text(encoding="utf-8", errors="replace")
    except OSError:  # pragma: no cover - unreadable manifest
        return out
    for line in text.splitlines():
        if line.startswith("# "):
            fields = line[2:].split()
            if fields and (d / fields[0]).is_dir():
                out[fields[0]] = d / fields[0]
    return out


#: A gem directory is ``<name>-<version>``; the version starts with a digit.
_GEM_DIR_RE = re.compile(r"^(?P<name>.+?)-\d[\w.\-]*$")


def _bundler_marker(d: Path) -> bool:
    """Bundler ``vendor/bundle`` (``bundle install --path vendor/bundle``):
    the candidate is ``bundle`` itself, inside ``vendor``, with ``Gemfile.lock``
    beside that ``vendor`` and the ``ruby/<abi>/`` layout Bundler writes.
    Keyed on ``bundle`` rather than ``vendor`` because a Rails ``vendor/`` also
    holds committed hand-placed code (``vendor/javascript``), which must stay."""
    return (
        d.parent.name == "vendor"
        and (d.parent.parent / "Gemfile.lock").is_file()
        and (d / "ruby").is_dir()
    )


def _bundler_packages(d: Path) -> dict[str, Path]:
    """``vendor/bundle/ruby/<abi>/gems/<name>-<version>``, named ``<name>``."""
    out: dict[str, Path] = {}
    for abi in _child_dirs(d / "ruby"):
        for g in _child_dirs(abi / "gems"):
            m = _GEM_DIR_RE.match(g.name)
            out[m.group("name") if m else g.name] = g
    return out


#: Directories CocoaPods writes into ``Pods/`` that are not pods.
_PODS_NON_PACKAGES = frozenset({
    "Target Support Files", "Local Podspecs", "Headers", "Pods.xcodeproj",
})


def _pods_marker(d: Path) -> bool:
    """CocoaPods ``Pods/``: ``Podfile.lock`` beside it and the
    ``Pods/Manifest.lock`` copy ``pod install`` writes."""
    return (d.parent / "Podfile.lock").is_file() and (d / "Manifest.lock").is_file()


def _pods_packages(d: Path) -> dict[str, Path]:
    return {
        c.name: c for c in _child_dirs(d)
        if c.name not in _PODS_NON_PACKAGES and not c.name.startswith(".")
    }


def _venv_marker(d: Path) -> bool:
    return _looks_like_virtualenv(str(d))


#: Entries of ``site-packages`` that are install metadata, not importable code.
_SITE_PACKAGES_METADATA_SUFFIXES: tuple[str, ...] = (
    ".dist-info", ".egg-info", ".data", ".pth",
)


def _venv_packages(d: Path) -> dict[str, Path]:
    """Importable top-level names in the virtualenv's ``site-packages``
    (``lib/python*/site-packages`` on POSIX, ``Lib/site-packages`` on
    Windows): a package directory or a single-module ``<name>.py``. Named by
    IMPORT name (``yaml``, not ``PyYAML``) -- the directory name is all the
    layout gives without reading install metadata."""
    sites = [lib / "site-packages" for lib in _child_dirs(d / "lib")]
    sites.append(d / "Lib" / "site-packages")
    out: dict[str, Path] = {}
    for site in sites:
        try:
            entries = sorted(site.iterdir())
        except OSError:
            continue
        for e in entries:
            if e.name.startswith(".") or e.name == "__pycache__" or e.is_symlink():
                continue
            if e.name.endswith(_SITE_PACKAGES_METADATA_SUFFIXES):
                continue
            if e.is_dir():
                out[e.name] = e
            elif e.suffix == ".py":
                out[e.stem] = e
    return out


def _sibling_file(*names: str) -> Callable[[Path], bool]:
    """Marker: one of ``names`` sits beside the candidate directory."""
    def check(d: Path) -> bool:
        return any((d.parent / n).is_file() for n in names)
    return check


def _phoenix_assets_marker(d: Path) -> bool:
    """Phoenix ``priv/static/assets``: the esbuild/tailwind output directory
    ``mix assets.build`` writes, identified by its full ``priv/static/assets``
    position under a directory holding ``mix.exs``. ``assets`` alone is far
    too common a name to condition on anything less."""
    static = d.parent
    priv = static.parent
    return (
        static.name == "static"
        and priv.name == "priv"
        and (priv.parent / "mix.exs").is_file()
    )


@dataclass(frozen=True)
class ContentRule:
    """One {candidate directory name, content marker} registry entry.

    ``dir_name`` only SELECTS which directories get ``marker``; the marker
    decides. ``packages`` lists what the directory holds, keyed by the name a
    user passes to ``--trace-deps``; it is ``None`` for tool build output,
    which has no packages and no opt-in (ADR-0004 §"Installed dependency
    source" point 7). ``ecosystem`` is the display label used in the
    disclosure line.
    """

    dir_name: str
    ecosystem: str
    marker: Callable[[Path], bool]
    packages: Callable[[Path], dict[str, Path]] | None = None

    @property
    def is_installed_dep(self) -> bool:
        return self.packages is not None


#: Installed dependency source, per ecosystem. Not parsed unless traced
#: (``--trace-deps``), disclosed when skipped. Two entries may share a
#: candidate name (Composer and Go both use ``vendor``); the first whose marker
#: passes wins. NOT YET COVERED (no entry, so such a directory is analysed):
#: Carthage ``Carthage/Checkouts``, Yarn PnP ``.yarn/cache`` zips, Bower
#: ``bower_components``, Elm 0.18 ``elm-stuff/packages``, Swift PM
#: ``.build/checkouts``, Cargo ``vendor/`` (``cargo vendor``), Bundler outside
#: ``vendor/bundle``.
INSTALLED_DEP_RULES: tuple[ContentRule, ...] = (
    ContentRule("deps", "Mix", _mix_deps_marker, _mix_deps_packages),
    ContentRule("node_modules", "npm", _node_modules_marker, _node_modules_packages),
    ContentRule("vendor", "Composer", _composer_vendor_marker, _composer_vendor_packages),
    ContentRule("vendor", "Go module", _go_vendor_marker, _go_vendor_packages),
    ContentRule("bundle", "Bundler", _bundler_marker, _bundler_packages),
    ContentRule("Pods", "CocoaPods", _pods_marker, _pods_packages),
    *(
        ContentRule(name, "Python virtualenv", _venv_marker, _venv_packages)
        for name in sorted(VENV_DIR_NAMES)
    ),
)

#: Tool build output and tool state that is conditioned on content because the
#: name alone is too generic (``cover``, ``assets``) or is shared with source
#: elsewhere. Always pruned, no opt-in, not disclosed -- like ``_build``.
#: ``.dart_tool``, ``.stack-work`` and ``elm-stuff`` (Elm 0.19) hold generated
#: code and build products; Dart, Stack and Elm keep package SOURCE in a
#: per-user cache outside the repository, so there is nothing to trace.
#: NOT YET COVERED: Phoenix ``mix phx.digest`` output (``priv/static/*-<hash>.*``
#: beside ``cache_manifest.json``), which is per-file, not per-directory.
BUILD_OUTPUT_RULES: tuple[ContentRule, ...] = (
    ContentRule("cover", "Mix coverage report", _sibling_file("mix.exs")),
    ContentRule("assets", "Phoenix built assets", _phoenix_assets_marker),
    ContentRule(".dart_tool", "Dart tool state", _sibling_file("pubspec.yaml")),
    ContentRule(".stack-work", "Stack build output", _sibling_file("stack.yaml")),
    ContentRule("elm-stuff", "Elm build output", _sibling_file("elm.json")),
)

_RULES_BY_NAME: dict[str, tuple[ContentRule, ...]] = {}
for _rule in (*INSTALLED_DEP_RULES, *BUILD_OUTPUT_RULES):
    _RULES_BY_NAME[_rule.dir_name] = (*_RULES_BY_NAME.get(_rule.dir_name, ()), _rule)
del _rule

#: Every directory name some content rule examines.
CONTENT_RULE_DIR_NAMES: frozenset[str] = frozenset(_RULES_BY_NAME)


@functools.lru_cache(maxsize=4096)
def _is_committed_dir(directory: str) -> bool:
    """Does HEAD's tree hold a non-dot file under ``directory``?

    THE DECISION (owner, 2026-10-06; ADR-0004 §"Installed dependency source"
    point 3): a directory whose files are committed is vendored code, never
    "installed" -- even when it carries a package manager's marker, as a
    committed ``go mod vendor`` tree carries ``vendor/modules.txt``. It is
    analysed and classified tier 3. A fresh clone holds the same files, which
    is the point of the policy: a dev box and a clone of one commit agree.

    HOW, AND WHY NOT ``git ls-files``. One ``git ls-tree --name-only HEAD --
    <name>/`` per marker-positive candidate (a handful per repository, zero in
    most), cached. ``ls-tree`` reads tree objects only. ``ls-files`` reads the
    INDEX, and reading the index with ``core.fsmonitor`` configured runs a
    program the analysed repository names -- the same class of hazard that
    removed ``git status`` from ``repo_fingerprint`` (see its module
    docstring). Consequence: "committed" means present in HEAD; a tree that is
    only staged counts as not committed. Children that are all dot-files
    (``.gitkeep``, ``.gitignore``) do not count -- a placeholder that keeps an
    empty ``vendor/`` in the tree does not make the installed contents
    committed.

    Fails open to "not committed" (markers then decide): no git binary, not a
    work tree, no commits yet, or any git error. ``GIT_DIR`` and friends are
    dropped from the child environment so an ambient hook environment cannot
    point the query at a different repository; ``GIT_NO_LAZY_FETCH`` keeps a
    partial clone from fetching over the network.
    """
    import os
    import shutil
    import subprocess  # nosec B404 - only for SubprocessError; the call goes through repo_inspect_git

    from .safety_zones import repo_inspect_git

    git = shutil.which("git")
    if git is None:  # pragma: no cover - git is installed wherever the suite runs
        return False
    d = Path(directory)
    env = {
        k: v for k, v in os.environ.items()
        if k not in ("GIT_DIR", "GIT_WORK_TREE", "GIT_INDEX_FILE",
                     "GIT_OBJECT_DIRECTORY", "GIT_COMMON_DIR")
    }
    env["GIT_NO_LAZY_FETCH"] = "1"
    try:
        proc = repo_inspect_git(
            [git, "ls-tree", "--name-only", "HEAD", "--", f"{d.name}/"],
            cwd=d.parent, capture_output=True, text=True, check=False,
            env=env, timeout=30,
        )
    except (OSError, subprocess.SubprocessError):  # pragma: no cover - defensive
        return False
    if proc.returncode != 0:
        return False
    return any(
        line and not line.rsplit("/", 1)[-1].startswith(".")
        for line in proc.stdout.splitlines()
    )


@functools.lru_cache(maxsize=8192)
def _match_content_rule(directory: str, name: str) -> ContentRule | None:
    path = Path(directory)
    if not path.is_dir() or path.is_symlink():
        return None
    for rule in _RULES_BY_NAME.get(name, ()):
        if rule.marker(path):
            return None if _is_committed_dir(directory) else rule
    return None


def match_content_rule(path: Path) -> ContentRule | None:
    """The content rule that claims directory ``path``, or ``None``.

    THE single test for "is this installed dependency source / tool build
    output". The name selects candidate rules (a set lookup, so every other
    directory costs nothing); the first rule whose marker passes claims the
    directory unless it is committed (:func:`_is_committed_dir`). Cached per
    path: discovery asks once per candidate per walk and the answer cannot
    change within a run.
    """
    if path.name not in CONTENT_RULE_DIR_NAMES:
        return None
    return _match_content_rule(str(path), path.name)


def under_content_rule_dir(repo_root: Path, dir_parts: "Iterable[str]") -> bool:
    """Does the repo-relative directory chain ``dir_parts`` pass through a
    directory a content rule claims (installed dependency source or
    content-conditioned build output)?

    For scans that glob or ``rglob`` rather than walk with
    :func:`is_pruned_dir` -- the profile's and sketch's manifest scans, the
    sketch's Additional Files candidates -- so ``deps/<pkg>/mix.exs`` is not
    read as a sub-project and ``node_modules/<pkg>/README.md`` is not
    offered as a project document.
    """
    parts = tuple(dir_parts)
    return any(
        match_content_rule(repo_root.joinpath(*parts[: i + 1])) is not None
        for i in range(len(parts))
    )


# ---------------------------------------------------------------------------
# --trace-deps: the per-package opt-in (ADR-0004 §"Installed dependency
# source" point 5)
# ---------------------------------------------------------------------------


def _fold_package_name(name: str) -> str:
    """Comparison key for package names: case-folded, ``-``/``_``/``.``
    unified, so ``--trace-deps typing-extensions`` finds ``typing_extensions``
    and ``Phoenix_HTML`` finds ``phoenix_html``. Applied to both sides."""
    return re.sub(r"[-_.]", "-", name.strip().lower())


@dataclass(frozen=True)
class TraceDeps:
    """Which installed dependency source to analyse.

    ``everything`` is ``--trace-deps all``; otherwise ``names`` holds the
    folded package names. The empty value (the default) traces nothing.
    """

    everything: bool = False
    names: frozenset[str] = frozenset()

    @property
    def is_empty(self) -> bool:
        return not self.everything and not self.names

    def traces(self, package: str) -> bool:
        return self.everything or _fold_package_name(package) in self.names

    def cache_token(self) -> str:
        """Stable, filesystem-safe token for the results-cache key; ``""``
        when nothing is traced, so every untraced cache entry keeps its key."""
        import hashlib

        if self.is_empty:
            return ""
        if self.everything:
            return "deps-all"
        digest = hashlib.sha256(",".join(sorted(self.names)).encode()).hexdigest()
        return f"deps-{digest[:12]}"

    @classmethod
    def parse(cls, spec: "str | Iterable[str] | None") -> "TraceDeps":
        """Parse ``"all"``, ``"none"``, ``"a,b"`` or a list of names.

        ``all`` traces everything, ``none`` (or an empty value) nothing. Raises
        ``ValueError`` when ``all``/``none`` is mixed with package names --
        ``--trace-deps all,phoenix`` has no single meaning.
        """
        if spec is None:
            return cls()
        items = spec.split(",") if isinstance(spec, str) else list(spec)
        names = [str(i).strip() for i in items if str(i).strip()]
        keywords = {n.lower() for n in names} & {"all", "none"}
        if keywords and len(names) > 1:
            raise ValueError(
                f"'{', '.join(names)}': 'all' and 'none' cannot be combined "
                f"with package names",
            )
        if not names or keywords == {"none"}:
            return cls()
        if keywords == {"all"}:
            return cls(everything=True)
        return cls(names=frozenset(_fold_package_name(n) for n in names))


#: The command-line value (``--trace-deps``) for the running command, or None
#: when the flag was not given. Set by ``cli.main`` around dispatch.
_trace_deps_override: TraceDeps | None = None

#: What the walk in progress applies, and the root it applies under. Set by
#: ``cli.run_survey`` for the duration of one analysis; empty otherwise, so
#: every other caller of :func:`find_files` / :func:`is_excluded` prunes all
#: installed dependency source.
_active_trace: TraceDeps = TraceDeps()
_active_trace_root: Path | None = None


def set_trace_deps_override(value: TraceDeps | None) -> None:
    """Record (or clear, with ``None``) the ``--trace-deps`` flag value."""
    global _trace_deps_override
    _trace_deps_override = value


def resolve_trace_deps(repo_root: Path) -> TraceDeps:
    """The effective setting for ``repo_root``: the flag if given, else the
    ``trace_deps`` key of the ADR-0045 user/project configuration, else
    nothing. Used by the analysis AND by the results-cache key, so the two
    cannot disagree. An unreadable config resolves to nothing here; the
    analysis itself reports a bad config and exits 2 before it walks."""
    if _trace_deps_override is not None:
        return _trace_deps_override
    from .user_config import ConfigError, load_layered_config

    try:
        return load_layered_config(repo_root=repo_root).trace_deps
    except ConfigError:
        return TraceDeps()


def set_active_trace_deps(value: TraceDeps, repo_root: Path | None) -> None:
    """Install the policy the next walks apply (``cli.run_survey``)."""
    global _active_trace, _active_trace_root
    _active_trace = value
    _active_trace_root = repo_root


@functools.lru_cache(maxsize=1024)
def _package_map(directory: str, rule: ContentRule) -> dict[str, Path]:
    assert rule.packages is not None
    return rule.packages(Path(directory))


def installed_packages(path: Path, rule: ContentRule) -> dict[str, Path]:
    """The packages installed dependency directory ``path`` holds."""
    return _package_map(str(path), rule)


def _traced_paths(root: Path, rule: ContentRule, trace: TraceDeps) -> list[Path]:
    return [
        p for name, p in installed_packages(root, rule).items() if trace.traces(name)
    ]


def _nearest_installed_root(path: Path) -> tuple[Path, ContentRule] | None:
    """The innermost installed-dependency directory strictly above ``path``,
    searched no higher than the active root (a repository that itself lives
    under someone's ``deps/`` is not inside installed source)."""
    for anc in path.parents:
        if _active_trace_root is not None and (
            anc == _active_trace_root or not anc.is_relative_to(_active_trace_root)
        ):
            return None
        if anc.name in CONTENT_RULE_DIR_NAMES:
            rule = match_content_rule(anc)
            if rule is not None and rule.is_installed_dep:
                return anc, rule
    return None


def content_rule_prunes(name: str, path: Path) -> bool:
    """Does the content-rule arm prune ``path`` (a directory or a file)?

    1. ``path`` is claimed by a rule: build output is always pruned; installed
       dependency source is pruned unless ``--trace-deps`` traces all of it
       or at least one of its packages.
    2. Per-package tracing (``--trace-deps a,b``): inside an installed
       directory only the traced packages survive -- ``path`` is kept when it
       IS a traced package, lies inside one, or is a directory on the way to
       one (``node_modules/@scope``, ``lib/python3.12``). A file sitting in
       such an on-the-way directory is not a package and is pruned.
    """
    trace = _active_trace
    rule = match_content_rule(path) if name in CONTENT_RULE_DIR_NAMES else None
    if rule is not None:
        if not rule.is_installed_dep:
            return True
        if trace.everything:
            return False
        return not _traced_paths(path, rule, trace)
    if not trace.names:
        return False
    found = _nearest_installed_root(path)
    if found is None:
        return False
    allowed = _traced_paths(*found, trace)
    return not any(
        path == a or path.is_relative_to(a) or a.is_relative_to(path)
        for a in allowed
    )


def installed_deps_summary(
    roots: "Iterable[tuple[Path, ContentRule]]",
    repo_root: Path,
    trace: TraceDeps,
) -> dict[str, Any]:
    """``supply_chain_summary.installed_deps_skipped`` for the installed
    directories a walk met (``FileIndex.installed_dep_roots``).

    One entry per directory with packages left unanalysed -- ``packages``
    counts the skipped ones, ``traced`` names the ones analysed under a
    per-package ``--trace-deps``. ``dirs`` and ``packages`` are totals over
    every entry; ``entries`` is capped at 10, like ``derived_skipped.paths``.
    Sizes are not reported: measuring one walks the tree the skip exists to
    avoid. A directory with no packages (only ``.bin``) is still an entry,
    with ``packages: 0`` -- its files were skipped.
    """
    entries: list[dict[str, Any]] = []
    for root, rule in roots:
        if trace.everything:
            continue
        pkgs = installed_packages(root, rule)
        traced = sorted(n for n in pkgs if trace.traces(n))
        skipped = len(pkgs) - len(traced)
        if pkgs and skipped == 0:
            continue
        try:
            rel = root.relative_to(repo_root).as_posix()
        except ValueError:  # pragma: no cover - the walk only yields children
            rel = root.as_posix()
        entries.append({
            "path": rel,
            "ecosystem": rule.ecosystem,
            "packages": skipped,
            "traced": traced,
        })
    entries.sort(key=lambda e: str(e["path"]))
    return {
        "dirs": len(entries),
        "packages": sum(e["packages"] for e in entries),
        "entries": entries[:10],
    }


#: The opt-in hint closing every disclosure line.
TRACE_DEPS_HINT = "To trace into them: --trace-deps <pkg,...|all>"


def format_installed_deps_disclosure(summary: "dict[str, Any] | None") -> str | None:
    """The one-line disclosure, or ``None`` when nothing was skipped.

    ``Installed dependency source not analysed: deps/ (81 Mix packages).
    Calls into them appear as external stubs. To trace into them:
    --trace-deps <pkg,...|all>`` -- naming at most three directories.
    """
    if not summary or not summary.get("dirs"):
        return None
    entries = summary.get("entries") or []
    parts = []
    for e in entries[:3]:
        n = e["packages"]
        noun = "package" if n == 1 else "packages"
        parts.append(f"{e['path']}/ ({n} {e['ecosystem']} {noun})")
    more = int(summary["dirs"]) - len(parts)
    if more > 0:
        parts.append(f"{more} more director{'y' if more == 1 else 'ies'}")
    return (
        f"Installed dependency source not analysed: {', '.join(parts)}. "
        f"Calls into them appear as external stubs. {TRACE_DEPS_HINT}"
    )


def walks_into(entry: Path, skip: "Iterable[str]" = ()) -> bool:
    """May a hand-written repository walk descend into ``entry``? (INV-pivir)

    A real directory whose name is neither in ``skip`` nor dot-prefixed -- and
    NEVER a directory SYMLINK. ``os.walk`` (``followlinks=False``) and
    ``Path.rglob`` already refuse to follow one; the iterative ``iterdir()``
    walks that read a repository's own manifests and source roots did not,
    because ``Path.is_dir()`` follows the link. A link back to an ancestor --
    arti's ``maint/rust-maint-common/{maint,common} -> .``, two self-links per
    level -- then makes the walk exponential, and ``verify-claims`` sat at 100%
    CPU for 30+ minutes before any analysis ran. Every such walk asks this, so
    the rule cannot be fixed in one walker and forgotten in the next.

    Nor into a directory a content rule claims (:func:`match_content_rule`) --
    installed dependency source or tool build output -- whatever
    ``--trace-deps`` says. These walks read the PROJECT's own manifests and
    source roots; a dependency's ``mix.exs`` or ``pyproject.toml`` names a
    third-party package, never the project.
    """
    return (
        entry.is_dir()
        and not entry.is_symlink()
        and entry.name not in set(skip)
        and not entry.name.startswith(".")
        and match_content_rule(entry) is None
    )


#: Names hand-written PROJECT-manifest walks skip on top of
#: :data:`DEFAULT_EXCLUDES` and :func:`walks_into`'s content test.
#: ``node_modules`` and ``vendor`` left ``DEFAULT_EXCLUDES`` when installed
#: dependency source became content-conditioned; for analysis that is right (a
#: committed ``vendor/`` is analysed as tier 3), but a manifest under either --
#: committed or not -- describes a dependency, never the project, so these
#: walks keep skipping them by name.
DEPENDENCY_DIR_NAMES: frozenset[str] = frozenset({"node_modules", "vendor"})


def manifest_walk_skip() -> set[str]:
    """The name set a project-manifest walk passes to :func:`walks_into`."""
    return set(DEFAULT_EXCLUDES) | DEPENDENCY_DIR_NAMES


def is_pruned_dir(
    name: str,
    abs_dir: Path,
    exact: frozenset[str],
    globs: tuple[str, ...],
) -> bool:
    """THE single rule for "should this directory be pruned from analysis".

    ONE RULE, ONE PLACE, EVERY WALKER. This repository has two independent tree
    walkers — :meth:`FileIndex.build`'s ``os.walk`` prune loop (the fast path every
    real run takes) and :func:`_is_excluded_classified` (the per-path check) — and
    they each carried their own copy of the membership test. When the venv rule below
    was first added to only one of them, ``find_files`` excluded a virtualenv
    correctly while a full ``run_behavior_map`` still analysed it: the same input,
    two answers. N places that should share one rule WILL drift, so they now call
    this. Parity is asserted behaviourally across all three public entry points by
    ``test_all_three_walkers_agree`` — structure-free, so it cannot be satisfied by a
    fourth copy that merely looks right.

    ``abs_dir`` is the absolute path of the directory named ``name``; it is only
    consulted for the content-rule arm (:func:`content_rule_prunes` --
    virtualenvs, the other installed dependency directories, and
    content-conditioned build output). ``_is_excluded_classified`` also passes
    the final FILE component through here, which is how per-package
    ``--trace-deps`` drops a stray file beside the traced packages on both
    walkers alike.
    """
    if name in exact:
        return True
    # Content-conditioned names. Skipped when the caller already listed the name
    # in ``exact`` — an explicit ``--exclude env`` is a direct instruction and is
    # obeyed literally; second-guessing it would be a different bug from the DEFAULT
    # this rule fixes.
    if content_rule_prunes(name, abs_dir):
        return True
    return any(fnmatch(name, pattern) for pattern in globs)


def _has_glob_chars(pattern: str) -> bool:
    """Check whether a pattern contains fnmatch glob characters."""
    return any(c in pattern for c in "*?[")


def _normalize_exclude_pattern(pattern: str) -> str:
    """Normalize a user-supplied exclude pattern to gitignore-style semantics.

    User intent for directory excludes is conveyed multiple ways that all
    mean "exclude this directory and its contents":

        ui            ui/           ui/**         **/ui/**         **/ui

    The pre-WI-zirik implementation matched patterns against each path part
    independently, so anything containing a '/' silently matched nothing.
    This helper collapses the four "directory under any depth" forms above
    into the bare name "ui" so per-part fnmatch handles them.

    For path-anchored patterns (e.g. ``cmd/server.go``), the leading and
    trailing decorations are stripped but the remaining ``/`` is preserved
    so the caller can recognise it as a relative-path pattern.
    """
    p = pattern.strip()
    if p.endswith("/"):
        p = p.rstrip("/")
    while p.startswith("**/"):
        p = p[3:]
    while p.endswith("/**"):
        p = p[:-3]
    # A pattern that reduces to bare '**' (or '/') is meaningless on its
    # own — it would match every name. Treat it as empty so the caller
    # drops it instead of silently widening the exclusion to all files.
    if p == "**":
        p = ""
    return p


def _classify_pattern(pattern: str) -> str:
    """Bucket a normalised pattern: 'empty', 'exact', 'glob', or 'path'.

    - 'empty': normalisation reduced the pattern to "" (e.g. ``/`` or ``**/``)
    - 'exact': bare directory/file name, no glob or slash
    - 'glob':  per-part fnmatch pattern (contains '*' '?' '[' but no '/')
    - 'path':  contains '/' — matched against the relative path string
    """
    if not pattern:
        return "empty"
    if "/" in pattern:
        return "path"
    if _has_glob_chars(pattern):
        return "glob"
    return "exact"


def _bucket_default_excludes() -> tuple[
    frozenset[str], tuple[str, ...], tuple[str, ...]
]:
    exact: set[str] = set()
    globs: list[str] = []
    paths: list[str] = []
    for raw in DEFAULT_EXCLUDES:
        p = _normalize_exclude_pattern(raw)
        kind = _classify_pattern(p)
        if kind == "exact":
            exact.add(p)
        elif kind == "glob":
            globs.append(p)
        elif kind == "path":  # pragma: no cover - DEFAULT_EXCLUDES has no path patterns today
            paths.append(p)
    return frozenset(exact), tuple(globs), tuple(paths)


# Pre-classify DEFAULT_EXCLUDES at module load time for fast matching.
# Exact names (no glob chars) use O(1) frozenset lookup; only the 3 glob
# patterns (*.egg-info, survey*.json, hypergumbo.results*.json) fall back to
# fnmatch.
(
    _EXACT_DEFAULT_EXCLUDES,
    _GLOB_DEFAULT_EXCLUDES,
    _PATH_DEFAULT_EXCLUDES,
) = _bucket_default_excludes()


def _classify_excludes(
    excludes: list[str],
) -> tuple[frozenset[str], tuple[str, ...], tuple[str, ...]]:
    """Split exclude patterns into exact names, glob patterns, and path patterns.

    Each pattern is first normalised (see ``_normalize_exclude_pattern``) so
    that ``ui``, ``ui/``, ``ui/**``, ``**/ui/**`` and ``**/ui`` all classify
    as the bare name ``ui``. Patterns that retain a ``/`` after normalisation
    are routed to the path bucket and matched against the relative path.

    Returns three buckets:
      - exact: O(1) frozenset of bare names
      - globs: per-part fnmatch patterns (e.g. ``*.egg-info``)
      - paths: relative-path fnmatch patterns (e.g. ``cmd/server.go``)
    """
    if excludes is DEFAULT_EXCLUDES:
        return _EXACT_DEFAULT_EXCLUDES, _GLOB_DEFAULT_EXCLUDES, _PATH_DEFAULT_EXCLUDES
    exact: set[str] = set()
    globs: list[str] = []
    paths: list[str] = []
    for raw in excludes:
        p = _normalize_exclude_pattern(raw)
        kind = _classify_pattern(p)
        if kind == "exact":
            exact.add(p)
        elif kind == "glob":
            globs.append(p)
        elif kind == "path":
            paths.append(p)
        # 'empty' is dropped silently — a pattern that normalises to ""
        # would otherwise match every path.
    return frozenset(exact), tuple(globs), tuple(paths)


def _is_excluded_classified(
    path: Path,
    repo_root: Path,
    exact: frozenset[str],
    globs: tuple[str, ...],
    paths: tuple[str, ...] = (),
) -> bool:
    """Fast exclusion check using pre-classified patterns.

    Uses frozenset membership for exact names and fnmatch only for
    the small number of glob patterns. Path-anchored patterns (containing
    '/') are matched against the full relative path string.
    """
    try:
        rel_path = path.relative_to(repo_root)
    except ValueError:
        rel_path = path

    # Base for reconstructing each component's absolute path. When ``relative_to``
    # succeeded the parts are repo-relative and must be rejoined onto ``repo_root``;
    # when it failed ``rel_path`` IS the original absolute path, so its own prefix
    # already reconstructs the directory. Getting this wrong silently disables the
    # venv content arm rather than erroring, so the two cases are named explicitly.
    base = repo_root if rel_path is not path else Path(rel_path.anchor)
    prefix = () if rel_path is not path else rel_path.parts[:1]
    for depth, part in enumerate(rel_path.parts):
        abs_dir = base.joinpath(*rel_path.parts[len(prefix):depth + 1])
        if is_pruned_dir(part, abs_dir, exact, globs):
            return True

    if paths:
        rel_str = rel_path.as_posix()
        for pattern in paths:
            if fnmatch(rel_str, pattern):
                return True

    return False


def is_excluded(path: Path, repo_root: Path, excludes: list[str] | None = None) -> bool:
    """Check if a path should be excluded from analysis.

    Args:
        path: The file or directory path to check
        repo_root: The repository root (for computing relative paths)
        excludes: List of exclude patterns (default: DEFAULT_EXCLUDES)

    Returns:
        True if the path should be excluded, False otherwise.

    Patterns are matched against each component of the relative path.
    For example, 'node_modules' matches any directory named 'node_modules'
    at any depth in the tree.
    """
    if excludes is None:
        excludes = DEFAULT_EXCLUDES

    exact, globs, paths = _classify_excludes(excludes)
    return _is_excluded_classified(path, repo_root, exact, globs, paths)


# ---------------------------------------------------------------------------
# FileIndex — single-pass file discovery cache
# ---------------------------------------------------------------------------

# Global file index. Set via set_file_index() before running analyzers;
# find_files() uses this to avoid redundant directory walks.
_global_file_index: "FileIndex | None" = None


def set_file_index(index: "FileIndex | None") -> None:
    """Set the global file index for find_files().

    Called by the CLI after building a FileIndex from a single os.walk()
    pass. When set, find_files() delegates to the index instead of
    calling rglob() per pattern, eliminating redundant directory walks.
    """
    global _global_file_index
    _global_file_index = index


def get_file_index() -> "FileIndex | None":
    """Get the current global file index, or None if not set."""
    return _global_file_index


class FileIndex:
    """Pre-computed index of all non-excluded files in a repository.

    Built from a single os.walk() pass at startup. Provides O(1)
    extension and filename lookups, and fnmatch-based glob matching
    against cached paths. Used by find_files() to avoid 80+ redundant
    directory walks per analysis run.

    Internal data structures:
    - _by_ext: maps lowercase extension (e.g. '.py') to list of Paths
    - _by_name: maps filename (e.g. 'Makefile') to list of Paths
    - _all_files: sorted list of all indexed files
    - _repo_root: the repository root used during construction
    """

    __slots__ = (
        "_all_files", "_by_ext", "_by_name", "_installed_dep_roots", "_repo_root",
    )

    def __init__(
        self,
        repo_root: Path,
        by_ext: dict[str, list[Path]],
        by_name: dict[str, list[Path]],
        all_files: list[Path],
        installed_dep_roots: "list[tuple[Path, ContentRule]] | None" = None,
    ) -> None:
        self._repo_root = repo_root
        self._by_ext = by_ext
        self._by_name = by_name
        self._all_files = all_files
        self._installed_dep_roots = installed_dep_roots or []

    @property
    def installed_dep_roots(self) -> "list[tuple[Path, ContentRule]]":
        """Installed-dependency directories the walk MET, pruned or traced
        (never one nested inside a pruned directory) -- the input to
        :func:`installed_deps_summary`."""
        return self._installed_dep_roots

    @classmethod
    def build(
        cls,
        repo_root: Path,
        excludes: list[str] | None = None,
        locale_excludes: list[Path] | None = None,
    ) -> "FileIndex":
        """Build a FileIndex from a single os.walk() pass.

        Args:
            repo_root: Repository root to walk.
            excludes: Exclude patterns (default: DEFAULT_EXCLUDES).
                Matched against each path component (same semantics as
                find_files).
            locale_excludes: Absolute directory paths to skip
                (locale-filtered doc dirs). If None, reads from the
                global locale_excludes setting.
        """
        import os

        if excludes is None:
            excludes = DEFAULT_EXCLUDES
        if locale_excludes is None:
            locale_excludes = _global_locale_excludes

        exact_exc, glob_exc, path_exc = _classify_excludes(excludes)

        by_ext: dict[str, list[Path]] = {}
        by_name: dict[str, list[Path]] = {}
        all_files: list[Path] = []
        installed_roots: list[tuple[Path, ContentRule]] = []
        # Per-package --trace-deps is the one mode in which a FILE can be
        # pruned by the content-rule arm (a stray file beside the traced
        # packages); every other mode skips that per-file check entirely.
        per_package = bool(_active_trace.names)

        for dirpath_str, dirnames, filenames in os.walk(repo_root):
            dirpath = Path(dirpath_str)

            # Prune excluded directories in-place (prevents os.walk
            # from descending into them). Path-anchored patterns are
            # checked separately below because they need a full
            # relative path for fnmatch.
            kept_dirs: list[str] = []
            for d in dirnames:
                if path_exc:
                    rel_dir = (dirpath / d).relative_to(repo_root).as_posix()
                    if any(
                        fnmatch(rel_dir, p) or rel_dir.startswith(p + "/")
                        for p in path_exc
                    ):
                        continue
                if d in exact_exc:
                    continue
                # Record every installed-dependency directory the walk meets,
                # pruned or traced: the disclosure is computed from these.
                rule = match_content_rule(dirpath / d)
                if rule is not None and rule.is_installed_dep:
                    installed_roots.append((dirpath / d, rule))
                # Shared with _is_excluded_classified — see is_pruned_dir for why
                # this is not an inline membership test any more.
                if is_pruned_dir(d, dirpath / d, exact_exc, glob_exc):
                    continue
                kept_dirs.append(d)
            dirnames[:] = kept_dirs

            # Prune locale-excluded directories
            if locale_excludes:
                dirnames[:] = [
                    d for d in dirnames
                    if not any(
                        (dirpath / d) == le or _is_child_of(dirpath / d, le)
                        for le in locale_excludes
                    )
                ]

            for fname in filenames:
                # Check filename-level excludes (e.g. package-lock.json)
                if fname in exact_exc:
                    continue
                if any(fnmatch(fname, g) for g in glob_exc):
                    continue
                if path_exc:
                    rel_file = (dirpath / fname).relative_to(repo_root).as_posix()
                    if any(fnmatch(rel_file, p) for p in path_exc):
                        continue
                if per_package and content_rule_prunes(fname, dirpath / fname):
                    continue

                fpath = dirpath / fname
                all_files.append(fpath)

                ext = fpath.suffix.lower()
                if ext:
                    by_ext.setdefault(ext, []).append(fpath)

                by_name.setdefault(fname, []).append(fpath)

        all_files.sort()
        for v in by_ext.values():
            v.sort()
        for v in by_name.values():
            v.sort()

        return cls(repo_root, by_ext, by_name, all_files, installed_roots)

    @classmethod
    def from_paths(cls, repo_root: Path, paths: Iterable[Path]) -> "FileIndex":
        """Build a FileIndex from an explicit list of files (no os.walk).

        INV-jumim: the sketch read-path uses this to scope filesystem
        discovery to a behavior map's own node paths. When ``sketch --input``
        summarizes a frozen behavior map, ``find_files`` and the Structure
        helpers must see the MAP's universe — not a re-walk of the current
        working directory, which both hung for 60+s on populated repos and
        produced a whole-repo sketch from a package-scoped map. Paths are
        deduplicated; ``by_ext`` / ``by_name`` mirror :meth:`build` so
        :meth:`match_pattern` (extension / filename / glob) behaves identically
        on a synthesized index. Excludes are NOT re-applied: the map's node
        paths are already the post-analysis universe.
        """
        by_ext: dict[str, list[Path]] = {}
        by_name: dict[str, list[Path]] = {}
        all_files: list[Path] = []
        seen: set[Path] = set()
        for fpath in paths:
            if fpath in seen:
                continue
            seen.add(fpath)
            all_files.append(fpath)
            ext = fpath.suffix.lower()
            if ext:
                by_ext.setdefault(ext, []).append(fpath)
            by_name.setdefault(fpath.name, []).append(fpath)
        all_files.sort()
        for v in by_ext.values():
            v.sort()
        for v in by_name.values():
            v.sort()
        return cls(repo_root, by_ext, by_name, all_files)

    @property
    def repo_root(self) -> Path:
        """The repository root this index was built from."""
        return self._repo_root

    def by_extension(self, *extensions: str) -> Iterator[Path]:
        """Yield files matching any of the given extensions.

        Extensions should include the dot, e.g. '.py', '.js'.
        """
        for ext in extensions:
            yield from self._by_ext.get(ext.lower(), [])

    def by_name(self, *names: str) -> Iterator[Path]:
        """Yield files matching any of the given exact filenames.

        E.g. by_name('Makefile', 'justfile').
        """
        for name in names:
            yield from self._by_name.get(name, [])

    def by_glob(self, *patterns: str) -> Iterator[Path]:
        """Yield files whose filename matches any of the given glob patterns.

        E.g. by_glob('Dockerfile*', '*.gradle.kts').
        Uses fnmatch against filenames (not full paths).
        """
        for fpath in self._all_files:
            for pat in patterns:
                if fnmatch(fpath.name, pat):
                    yield fpath
                    break  # avoid yielding same file for multiple patterns

    def all_files(self) -> list[Path]:
        """Return all indexed files."""
        return self._all_files

    def match_pattern(self, pattern: str) -> Iterator[Path]:
        """Match a single pattern using the best strategy.

        Classifies the pattern as:
        - Pure extension ('*.py') → O(1) dict lookup
        - Exact filename ('Makefile') → O(1) dict lookup
        - Glob ('Dockerfile*', '*.gradle.kts') → fnmatch scan

        Handles '**/' prefix (stripped, since the index is already
        recursive).
        """
        # Strip leading **/ — the index is already recursive
        if pattern.startswith("**/"):
            pattern = pattern[3:]

        if not _has_glob_chars(pattern):
            # Exact filename: 'Makefile', 'justfile', etc.
            yield from self._by_name.get(pattern, [])
        elif (
            pattern.startswith("*.")
            and not _has_glob_chars(pattern[2:])
            and "." not in pattern[2:]
        ):
            # Pure single-extension: '*.py', '*.tsx'.
            # Compound suffixes like '*.blade.php', '*.d.ts', '*.lagda.md'
            # MUST NOT take this path — Path.suffix only retains the last
            # segment, so '_by_ext[".blade.php"]' would be empty and the
            # pattern would silently match zero files (WI-navaf: blade
            # analyzer was never enrolling on koel because of this).
            ext = pattern[1:]  # '.py', '.tsx'
            yield from self._by_ext.get(ext.lower(), [])
        else:
            # General glob: 'Dockerfile*', '*.gradle.kts', '*.blade.php', etc.
            for fpath in self._all_files:
                if fnmatch(fpath.name, pattern):
                    yield fpath

    def __len__(self) -> int:
        return len(self._all_files)


def _is_child_of(child: Path, parent: Path) -> bool:
    """Check if child is under parent directory.

    Defensive helper for locale exclude pruning. In practice, os.walk's
    in-place dirnames pruning prevents descending into excluded dirs,
    so this branch rarely fires. Kept for correctness if locale_excludes
    contains paths at varying depths.
    """
    try:
        child.relative_to(parent)
        return True  # pragma: no cover
    except ValueError:
        return False


def find_files(
    repo_root: Path,
    patterns: list[str],
    excludes: list[str] | None = None,
    max_files: int | None = None,
    max_file_bytes: int | None = None,
    on_file_skipped: Callable[[Path, int, str], None] | None = None,
) -> Iterator[Path]:
    """Find files matching patterns while respecting exclude rules.

    When a global FileIndex is set (via set_file_index()) for the same
    ``repo_root``, delegates to the index for O(1) lookups instead of
    calling rglob() per pattern. The index was built with its own
    excludes, and in that case the ``excludes`` argument is NOT applied:
    only ``repo_root`` is compared (WI-duhih).
    Falls back to rglob() when no index is installed for this root.

    Exclude patterns are classified once per call into exact names
    (frozenset lookup) and glob patterns (fnmatch). This avoids
    per-file pattern classification overhead.

    Args:
        repo_root: The repository root to search from
        patterns: List of glob patterns to match (e.g., ["*.py", "*.pyi"])
        excludes: List of exclude patterns (default: DEFAULT_EXCLUDES)
        max_files: Maximum number of files to return (None = unlimited)
        max_file_bytes: Skip files exceeding this size in bytes (None = no limit)
        on_file_skipped: Optional callback(path, size_bytes, reason) for skipped files

    Yields:
        Paths to files matching the patterns that are not excluded.
    """
    if excludes is None:
        excludes = DEFAULT_EXCLUDES

    # Use global limit if no explicit value provided
    if max_file_bytes is None:
        max_file_bytes = _global_max_file_bytes

    # Use global callback if no explicit callback provided
    if on_file_skipped is None:
        on_file_skipped = _global_on_file_skipped

    # Fast path: use the global file index if available.
    # The index was built with the same excludes and locale filtering,
    # so we only need to apply max_file_bytes filtering here.
    index = _global_file_index
    if index is not None and index.repo_root == repo_root:
        count = 0
        seen: set[Path] = set()
        for pattern in patterns:
            for path in index.match_pattern(pattern):
                if path in seen:
                    continue
                seen.add(path)
                if max_files is not None and count >= max_files:
                    return
                if max_file_bytes is not None:
                    try:
                        size = path.stat().st_size
                    except OSError:  # pragma: no cover
                        continue
                    if size > max_file_bytes:
                        if on_file_skipped is not None:
                            on_file_skipped(
                                path, size,
                                f"exceeds {max_file_bytes} bytes",
                            )
                        continue
                yield path
                count += 1
        return

    # Slow path: no index available, fall back to rglob()
    exact, globs, paths = _classify_excludes(excludes)

    count = 0
    for pattern in patterns:
        for path in repo_root.rglob(pattern):
            if max_files is not None and count >= max_files:
                return
            if not path.is_file():
                continue
            if _is_excluded_classified(path, repo_root, exact, globs, paths):
                continue
            if _is_under_locale_exclude(path):
                continue
            if max_file_bytes is not None:
                try:
                    size = path.stat().st_size
                except OSError:  # pragma: no cover
                    continue
                if size > max_file_bytes:
                    if on_file_skipped is not None:
                        on_file_skipped(
                            path, size,
                            f"exceeds {max_file_bytes} bytes",
                        )
                    continue
            yield path
            count += 1


def find_non_test_files(
    repo_root: Path,
    patterns: list[str],
    excludes: list[str] | None = None,
    max_files: int | None = None,
    max_file_bytes: int | None = None,
    on_file_skipped: Callable[[Path, int, str], None] | None = None,
) -> Iterator[Path]:
    """:func:`find_files`, minus test files (linker-evidence-gating:F1).

    Tier-2 content-scanning linkers (message-queue, database-query, http,
    graphql, grpc, websocket, …) regex-match framework patterns in file
    *content* and synthesize Symbols/Edges from the matches. A matching string
    literal sitting in a TEST file — a fixture, an assertion, an example in a
    regression test — would otherwise yield a phantom *production* edge:
    WI-nitob (the message-queue linker synthesized 103 ``event_publishes`` from
    MQ pattern strings in test-file bodies, cross-linking 26 unrelated test
    files by topic) and WI-rilin (the database-query linker emitted phantom
    cross-package table ``references`` sourced entirely from its own test
    files) are two filed P1 instances of the same class.

    This wrapper drops test-classified paths at the single discovery
    chokepoint via :func:`hypergumbo_core.paths.is_test_file` — the canonical
    filesystem-scan test-gate (the broad "test-OR-support" ranking/scan
    predicate, distinct from the narrow supply-chain role flag
    ``Symbol.is_test_file``; the two are kept separate by design, WI-popok) —
    so every linker that self-scans the filesystem gates on test status in ONE
    place — instead of each linker carrying (or omitting) its own private
    copy. Swapping a linker's ``find_files`` call for this one is therefore a
    no-new-branch change: the skip decision lives here, exercised by this
    module's own tests. Linkers that genuinely need to read test files (none
    today) should keep calling :func:`find_files` directly.

    The signature mirrors :func:`find_files` exactly and forwards every
    argument; only test-classified paths are additionally withheld.
    """
    for path in find_files(
        repo_root,
        patterns,
        excludes=excludes,
        max_files=max_files,
        max_file_bytes=max_file_bytes,
        on_file_skipped=on_file_skipped,
    ):
        if is_test_file(str(path)):
            continue
        yield path
