"""File discovery with exclude patterns and ambiguous extension disambiguation.

Provides shared utilities for finding source files across the repository while
respecting exclude patterns. Also provides content-based classification for
ambiguous file extensions:

- ``.m`` files: shared by Objective-C, MATLAB, and Wolfram.
  ``classify_dot_m_file`` reads file content and uses syntactic heuristics.
- ``.d`` files: shared by D programming language and GCC Makefile dependency
  files (generated by ``gcc -MMD``). ``classify_dot_d_file`` distinguishes
  D source from dependency files by checking for D keywords vs make rules.
"""
import re
from fnmatch import fnmatch
from pathlib import Path
from typing import Callable, Iterator

# Global file size limit. Set via set_max_file_bytes() before running
# analyzers; find_files() reads this when no explicit max_file_bytes
# is passed. Reset to None after use.
_global_max_file_bytes: int | None = None


def set_max_file_bytes(limit: int | None) -> None:
    """Set the global max file bytes limit for find_files().

    Called by the CLI before running analyzers so that all callers of
    find_files() respect the limit without needing individual changes.
    """
    global _global_max_file_bytes
    _global_max_file_bytes = limit


# Compiled patterns for .m file disambiguation — compiled once at import time.
# Objective-C: preprocessor directives and @-keywords
_OBJC_PATTERNS = re.compile(
    r"(?:^#import\b|^#include\b|^@interface\b|^@implementation\b"
    r"|^@protocol\b|^@end\b|^@property\b|^@synthesize\b|^@dynamic\b"
    r"|^#pragma\b)",
    re.MULTILINE,
)
# Wolfram: pattern-match arguments (x_), scoping constructs, package structure
_WOLFRAM_PATTERNS = re.compile(
    r"(?:\w+\[[\w_,\s]*\w+_[\w]*\]\s*:="  # f[x_] := or f[x_, y_Integer] :=
    r"|(?:Module|Block|With)\["            # scoping constructs
    r"|BeginPackage\[|EndPackage\["         # package structure
    r"|Needs\[|Get\["                       # imports
    r"|\(\*)",                              # block comments (* ... *)
    re.MULTILINE,
)
# MATLAB: function/classdef keywords at start of line
_MATLAB_PATTERNS = re.compile(
    r"(?:^function\b|^classdef\b)",
    re.MULTILINE,
)

# D language: keywords and attributes distinctive to D source code
_D_SOURCE_PATTERNS = re.compile(
    r"(?:^module\s+\w|^import\s+\w"       # module/import declarations
    r"|^(?:class|struct|interface|enum)\s"  # type definitions
    r"|^unittest\b"                         # unittest blocks
    r"|@(?:safe|trusted|nogc|system)\b"     # D-specific attributes
    r"|\bvoid\s+\w+\s*\("                  # void function defs
    r"|\bauto\s+\w+\s*=)",                 # auto variable defs
    re.MULTILINE,
)

# GCC dependency file: target.o: prerequisite.c header.h
# First line typically matches this pattern; we check only the first line
# to avoid false matches inside D source comments.
_GCC_DEP_PATTERN = re.compile(
    r"^\S+\.o\s*:\s*\S+\.\w",
)

# How many bytes to read for classification. 8 KB is enough to capture
# the file header, imports, and first few definitions.
_CLASSIFY_READ_LIMIT = 8192


def classify_dot_m_file(path: Path) -> str:
    """Classify a .m file as 'objc', 'wolfram', or 'matlab'.

    Uses content-based heuristics to disambiguate .m files, which are shared
    by three languages:
    - Objective-C: #import, @interface/@implementation/@protocol, #pragma
    - Wolfram/Mathematica: f[x_] :=, Module[, BeginPackage[, (* comments *)
    - MATLAB: function keyword, classdef keyword, % comments

    Reads the first 8 KB of the file for classification. Returns 'matlab' as
    the default when no strong signals are found (MATLAB is the most common
    user of .m files in practice).

    Args:
        path: Path to a .m file.

    Returns:
        One of 'objc', 'wolfram', or 'matlab'.
    """
    try:
        content = path.read_bytes()[:_CLASSIFY_READ_LIMIT].decode("utf-8", errors="replace")
    except (OSError, PermissionError):
        return "matlab"

    # Check Objective-C first — it has the most distinctive syntax
    if _OBJC_PATTERNS.search(content):
        return "objc"

    # Check Wolfram — pattern-match syntax (x_) is very distinctive
    if _WOLFRAM_PATTERNS.search(content):
        return "wolfram"

    # Check MATLAB keywords
    if _MATLAB_PATTERNS.search(content):
        return "matlab"

    # Default: MATLAB is the most common use of .m files
    return "matlab"


def classify_dot_d_file(path: Path) -> str:
    """Classify a .d file as 'd' (D language source) or 'dependency' (GCC).

    .d files are ambiguous: they can be D programming language source or GCC
    Makefile dependency files generated by ``gcc -MMD``.  Dependency files
    contain make-style ``target.o: prerequisite.c header.h`` rules and should
    not be analyzed as D source.

    .di files (D interface files) are always D source — no ambiguity.

    Reads the first 8 KB of the file for classification.  Returns 'd' as the
    default when no strong signals are found.

    Args:
        path: Path to a .d or .di file.

    Returns:
        One of 'd' or 'dependency'.
    """
    # .di files are always D interface files, no ambiguity
    if path.suffix == ".di":
        return "d"

    try:
        content = path.read_bytes()[:_CLASSIFY_READ_LIMIT].decode(
            "utf-8", errors="replace",
        )
    except (OSError, PermissionError):
        return "d"

    # Check D source patterns first — they are distinctive
    if _D_SOURCE_PATTERNS.search(content):
        return "d"

    # Check GCC dependency file pattern on the first non-empty line
    first_line = ""
    for line in content.split("\n"):
        stripped = line.strip()
        if stripped:
            first_line = stripped
            break
    if first_line and _GCC_DEP_PATTERN.match(first_line):
        return "dependency"

    # Default: assume D source (benefit of the doubt)
    return "d"


# Default exclude patterns (gitignore-style)
DEFAULT_EXCLUDES = [
    # Dependency directories
    "node_modules",
    "vendor",  # PHP (Composer), Go
    "venv",
    ".venv",
    "env",
    ".eggs",
    # Build output
    "dist",
    "build",
    "_build",  # Sphinx docs
    "out",
    "target",  # Rust, Maven
    # VCS and IDE
    ".git",
    ".svn",
    ".hg",
    # Caches
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    ".tox",
    ".nox",
    ".cache",
    "*.egg-info",
    ".terraform",  # Terraform providers and modules cache
    # Coverage and test reports
    "htmlcov",  # Python (pytest-cov)
    "coverage",  # Generic (Ruby, JS)
    ".coverage",  # Python coverage.py
    "coverage.xml",  # Python, generic (Cobertura format)
    ".nyc_output",  # JavaScript (nyc/Istanbul)
    "lcov-report",  # JavaScript/C++ (LCOV HTML)
    "lcov.info",  # JavaScript/C++ (LCOV data)
    ".c8_output",  # JavaScript (c8)
    "coverage.out",  # Go
    "cover.out",  # Go (alternate name)
    "cover.html",  # Go (HTML report)
    "tarpaulin-report",  # Rust (cargo-tarpaulin)
    "TestResults",  # .NET (dotnet test)
    "coverlet",  # .NET (Coverlet)
    "gcov-reports",  # C/C++ (gcov)
    "jest-coverage",  # JavaScript (Jest)
    ".jest",  # JavaScript (Jest cache)
    "snapshot_report.html",  # pytest-html snapshot report
    # Documentation output
    "site",  # mkdocs
    "_site",  # Jekyll
    # NOTE: Hugo uses public/ for generated output, but it's typically
    # gitignored.  Excluding "public" caused severe false positives:
    # Airflow routes/public/ (109 API handlers), Laravel/Symfony public/
    # (web root), etc.  Removed in v0.5.1.
    # Hypergumbo output artifacts
    ".hypergumbo",
    "hypergumbo.results*.json",  # Matches .json, .4k.json, .16k.json, .64k.json, etc.
    # Lock files - generated, inflate LOC counts
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "poetry.lock",
    "Pipfile.lock",
    "Gemfile.lock",
    "composer.lock",
    "Cargo.lock",
    "go.sum",
    "pubspec.lock",  # Dart/Flutter
    "packages.lock.json",  # NuGet (.NET)
]


def _has_glob_chars(pattern: str) -> bool:
    """Check whether a pattern contains fnmatch glob characters."""
    return any(c in pattern for c in "*?[")


# Pre-classify DEFAULT_EXCLUDES at module load time for fast matching.
# Exact names (no glob chars) use O(1) frozenset lookup; only the 2 glob
# patterns (*.egg-info, hypergumbo.results*.json) fall back to fnmatch.
_EXACT_DEFAULT_EXCLUDES = frozenset(
    p for p in DEFAULT_EXCLUDES if not _has_glob_chars(p)
)
_GLOB_DEFAULT_EXCLUDES = tuple(
    p for p in DEFAULT_EXCLUDES if _has_glob_chars(p)
)


def _classify_excludes(
    excludes: list[str],
) -> tuple[frozenset[str], tuple[str, ...]]:
    """Split exclude patterns into exact names and glob patterns.

    Exact names are matched via frozenset membership (O(1) per check).
    Glob patterns are matched via fnmatch (O(n) per check, but n is
    typically 2 for DEFAULT_EXCLUDES).
    """
    if excludes is DEFAULT_EXCLUDES:
        return _EXACT_DEFAULT_EXCLUDES, _GLOB_DEFAULT_EXCLUDES
    exact = frozenset(p for p in excludes if not _has_glob_chars(p))
    globs = tuple(p for p in excludes if _has_glob_chars(p))
    return exact, globs


def _is_excluded_classified(
    path: Path,
    repo_root: Path,
    exact: frozenset[str],
    globs: tuple[str, ...],
) -> bool:
    """Fast exclusion check using pre-classified patterns.

    Uses frozenset membership for exact names and fnmatch only for
    the small number of glob patterns.
    """
    try:
        rel_path = path.relative_to(repo_root)
    except ValueError:
        rel_path = path

    for part in rel_path.parts:
        if part in exact:
            return True
        for pattern in globs:
            if fnmatch(part, pattern):
                return True

    return False


def is_excluded(path: Path, repo_root: Path, excludes: list[str] | None = None) -> bool:
    """Check if a path should be excluded from analysis.

    Args:
        path: The file or directory path to check
        repo_root: The repository root (for computing relative paths)
        excludes: List of exclude patterns (default: DEFAULT_EXCLUDES)

    Returns:
        True if the path should be excluded, False otherwise.

    Patterns are matched against each component of the relative path.
    For example, 'node_modules' matches any directory named 'node_modules'
    at any depth in the tree.
    """
    if excludes is None:
        excludes = DEFAULT_EXCLUDES

    exact, globs = _classify_excludes(excludes)
    return _is_excluded_classified(path, repo_root, exact, globs)


def find_files(
    repo_root: Path,
    patterns: list[str],
    excludes: list[str] | None = None,
    max_files: int | None = None,
    max_file_bytes: int | None = None,
    on_file_skipped: Callable[[Path, int, str], None] | None = None,
) -> Iterator[Path]:
    """Find files matching patterns while respecting exclude rules.

    Exclude patterns are classified once per call into exact names
    (frozenset lookup) and glob patterns (fnmatch). This avoids
    per-file pattern classification overhead.

    Args:
        repo_root: The repository root to search from
        patterns: List of glob patterns to match (e.g., ["*.py", "*.pyi"])
        excludes: List of exclude patterns (default: DEFAULT_EXCLUDES)
        max_files: Maximum number of files to return (None = unlimited)
        max_file_bytes: Skip files exceeding this size in bytes (None = no limit)
        on_file_skipped: Optional callback(path, size_bytes, reason) for skipped files

    Yields:
        Paths to files matching the patterns that are not excluded.
    """
    if excludes is None:
        excludes = DEFAULT_EXCLUDES

    # Use global limit if no explicit value provided
    if max_file_bytes is None:
        max_file_bytes = _global_max_file_bytes

    # Classify once, use for all files in this call
    exact, globs = _classify_excludes(excludes)

    count = 0
    for pattern in patterns:
        for path in repo_root.rglob(pattern):
            if max_files is not None and count >= max_files:
                return
            if not path.is_file():
                continue
            if _is_excluded_classified(path, repo_root, exact, globs):
                continue
            if max_file_bytes is not None:
                try:
                    size = path.stat().st_size
                except OSError:  # pragma: no cover
                    continue
                if size > max_file_bytes:
                    if on_file_skipped is not None:
                        on_file_skipped(
                            path, size,
                            f"exceeds {max_file_bytes} bytes",
                        )
                    continue
            yield path
            count += 1
