# SPDX-License-Identifier: AGPL-3.0-or-later
"""Tests for the vendored Sourcegraph SCIP protobuf binding.

``scip_pb2.py`` is auto-generated by ``scripts/build-scip-proto`` from a
pinned revision of Sourcegraph's ``scip.proto``. The generated file is
checked in (WI-mafut discussion path B) because no PyPI package
publishes a ready-made SCIP Python binding. These tests enforce that:

* The generated module imports without raising. A broken generator or
  protobuf major-version mismatch would surface here, not in downstream
  shim code whose stack traces are harder to read.
* Every message type the WI-mafut Phase 2+ shims will consume is
  present. A silent rename upstream (e.g. Sourcegraph renaming
  ``SymbolInformation`` to ``Symbol``) would fail this test immediately
  rather than after we have written several shim modules against the
  old name.
* An ``Index`` survives a serialize -> parse round-trip. This guards
  against subtle protobuf encoding regressions in the vendored file
  itself (e.g. a hand-edit to scip_pb2.py corrupting a field tag).
* ``SOURCE_COMMIT.txt`` contains a 40-char hex SHA so the pin is
  reproducible. Bumping the pin requires rerunning the build script.
"""
from __future__ import annotations

import re
from pathlib import Path


def test_generated_module_imports() -> None:
    from hypergumbo_core.scip._generated import scip_pb2

    assert scip_pb2 is not None


def test_expected_message_types_present() -> None:
    from hypergumbo_core.scip._generated import scip_pb2

    expected = (
        "Index",
        "Metadata",
        "ToolInfo",
        "Document",
        "SymbolInformation",
        "Occurrence",
        "Relationship",
        "Diagnostic",
        "SymbolRole",
        "SyntaxKind",
    )
    for name in expected:
        assert hasattr(scip_pb2, name), f"scip_pb2 is missing {name!r}"


def test_index_roundtrip() -> None:
    from hypergumbo_core.scip._generated import scip_pb2

    doc = scip_pb2.Document(
        language="rust",
        relative_path="src/lib.rs",
        symbols=[
            scip_pb2.SymbolInformation(
                symbol="rust-analyzer cargo my_crate 0.1.0 foo()."
            )
        ],
    )
    idx = scip_pb2.Index(documents=[doc])
    wire = idx.SerializeToString()

    parsed = scip_pb2.Index()
    parsed.ParseFromString(wire)

    assert len(parsed.documents) == 1
    assert parsed.documents[0].language == "rust"
    assert parsed.documents[0].relative_path == "src/lib.rs"
    assert len(parsed.documents[0].symbols) == 1
    assert parsed.documents[0].symbols[0].symbol == (
        "rust-analyzer cargo my_crate 0.1.0 foo()."
    )


def test_source_commit_file_is_pinned_sha() -> None:
    from hypergumbo_core.scip import _generated

    commit_file = Path(_generated.__file__).parent / "SOURCE_COMMIT.txt"
    sha = commit_file.read_text().strip()
    assert re.fullmatch(r"[0-9a-f]{40}", sha), (
        f"SOURCE_COMMIT.txt must record a 40-char hex SHA; got {sha!r}"
    )
