# SPDX-License-Identifier: AGPL-3.0-or-later
"""ONE predicate answers "does this file announce itself as generated"
(INV-bokim + INV-pogob).

TWO PREDICATES, ONE QUESTION, DIFFERENT ANSWERS, in the same module:

  ``supply_chain._GENERATED_HEADER_PATTERN`` -- STRICT. Comment-anchored, and
    one of ``@generated`` / ``Code generated by ... DO NOT EDIT`` /
    ``Autogenerated`` / ``AUTO-GENERATED`` / ``automatically generated``. Feeds
    the ``is_generated`` FLAG on a classification.

  ``supply_chain.is_likely_minified`` heuristic 3 -- LOOSE.
    ``re.search(r"(Generated by|@generated|DO NOT EDIT)", head, re.IGNORECASE)``
    over the first five lines, no comment prefix required. Feeds the TIER, and
    ``Tier.DERIVED`` DROPS EVERY SYMBOL IN THE FILE.

The loose one won, because ``_classify_file_core`` consults it at step 2 and
returns immediately. So the more destructive consumer had the weaker rule.

WHAT THAT COST, both measured on real files rather than argued:

  INV-bokim, on hypergumbo's OWN repository. Two hand-written first-party test
  files contributed ZERO nodes to a default survey --
  ``test_spec_linker_count.py`` and ``test_scip_generated.py`` -- because their
  DOCSTRINGS mention some OTHER file being generated ("``docs/ARCHITECTURE.md``
  is regenerated by ``scripts/generate-architecture``"). ``"regenerated by"``
  contains ``"generated by"`` as a substring, the search is case-insensitive and
  unanchored, and ``test_ir.py`` (186 nodes) is the control that shows the
  survey was otherwise working.

  INV-pogob, on Go. ``scripts/measure-catalogue-reach.py`` was excluding its own
  fixture and reported 0 of 210 Go primitives reachable; only the instrument's
  positive control stopped that number from shipping. Identical file body, only
  the header differing: no header -> 2 boundary calls; ``// leading comment`` ->
  2; ``// generated by scripts/measure-catalogue-reach.py`` -> 0.

THE UNION IS THE RULE, NOT THE STRICT SET. Collapsing onto
``_GENERATED_HEADER_PATTERN`` as it stood would have lost a real detection: the
Python protobuf compiler writes ``# Generated by the protocol buffer compiler.
DO NOT EDIT!``, which is not ``Code generated by``. The shared rule is therefore
COMMENT-ANCHORED plus a marker set that keeps the weak phrase ``generated by``
ONLY when ``DO NOT EDIT`` co-occurs on the same line -- which is what makes it a
generator's declaration rather than a sentence about one.
"""

from pathlib import Path

import pytest

from hypergumbo_core.supply_chain import (
    Tier,
    classify_file,
    is_likely_minified,
    _has_generated_header,
)

#: (filename, source, expected). Each row is a real observed header shape, not
#: an invented one: the two defects come from INV-bokim / INV-pogob's own
#: measurements, and the positives are what real generators emit.
CASES: list[tuple[str, str, bool]] = [
    # --- the two filed defects -----------------------------------------
    ("t_docstring.py",
     '"""Doc that says ``docs/ARCHITECTURE.md`` is regenerated by\n'
     '``scripts/generate-architecture``."""\n'
     "import os\n\n\ndef f():\n    return os.getcwd()\n",
     False),
    ("probe.go",
     "// generated by scripts/measure-catalogue-reach.py\n"
     "package main\n\nfunc f() {}\n",
     False),
    # --- controls: the defects' own negatives --------------------------
    ("plain.py", '"""Ordinary docstring."""\nimport os\n\n\ndef f():\n    pass\n',
     False),
    ("plain.go", "// leading comment\npackage main\n\nfunc f() {}\n", False),
    # --- controls: real generators, which must keep firing -------------
    ("proto_pb2.py",
     "# Generated by the protocol buffer compiler.  DO NOT EDIT!\n"
     "# source: myproto.proto\n\nclass MyMessage:\n    pass\n",
     True),
    ("types.go",
     "// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage api\n",
     True),
    ("Schema.java",
     "// @generated by some-tool v1.2.3\n\npublic class Schema {}\n",
     True),
    ("api.ts",
     "// @generated by openapi-typescript\nexport interface User {}\n",
     True),
    ("gen.py",
     "# Autogenerated from a template. Do not modify.\nX = 1\n",
     True),
    ("gen.xml",
     "<!-- AUTO-GENERATED FILE -->\n<root/>\n",
     True),
]


@pytest.mark.parametrize("name,source,expected", CASES)
def test_the_two_consumers_give_the_same_answer(
    name: str, source: str, expected: bool, tmp_path: Path,
) -> None:
    """The point of the fix, stated as one assertion.

    ``_has_generated_header`` (the ``is_generated`` flag) and
    ``is_likely_minified``'s generator heuristic (the tier) must agree on every
    row, because they are asking one question. Before this they disagreed on
    four of the ten rows below, and the destructive consumer held the weaker
    rule.
    """
    target = tmp_path / name
    target.write_text(source)
    assert _has_generated_header(target) is expected
    assert is_likely_minified(target) is expected


@pytest.mark.parametrize("name,source,expected", CASES)
def test_the_tier_follows(
    name: str, source: str, expected: bool, tmp_path: Path,
) -> None:
    """And the consequence a reader actually sees: ``Tier.DERIVED`` drops every
    symbol in the file, so this is where INV-bokim's two first-party test files
    lost all 186-node-scale content."""
    target = tmp_path / name
    target.write_text(source)
    result = classify_file(target, tmp_path)
    assert (result.tier is Tier.DERIVED) is expected, result.reason
    assert result.is_generated is expected


class TestTheAnchorAndTheCoOccurrenceAreBothLoadBearing:
    """Each half of the shared rule, pinned separately, because dropping either
    reintroduces one of the two filed defects."""

    def test_an_unanchored_marker_does_not_fire(self, tmp_path: Path) -> None:
        """INV-bokim: prose ABOUT generated code is not a declaration. This is
        the exact sentence from ``test_scip_generated.py``'s docstring."""
        p = tmp_path / "t.py"
        p.write_text(
            '"""``scip_pb2.py`` is auto-generated by ``scripts/build-scip-proto``\n'
            'from a schema. DO NOT EDIT it by hand."""\n\nX = 1\n'
        )
        assert is_likely_minified(p) is False
        assert _has_generated_header(p) is False

    def test_the_weak_phrase_needs_do_not_edit(self, tmp_path: Path) -> None:
        """INV-pogob: ``// generated by <script>`` is how humans annotate a
        checked-in artefact they still edit; ``DO NOT EDIT`` is what makes it a
        generator's declaration."""
        without = tmp_path / "a.go"
        without.write_text("// generated by tool\npackage main\n")
        with_marker = tmp_path / "b.go"
        with_marker.write_text("// generated by tool. DO NOT EDIT.\npackage main\n")
        assert is_likely_minified(without) is False
        assert is_likely_minified(with_marker) is True

    def test_a_bare_do_not_edit_comment_still_fires(self, tmp_path: Path) -> None:
        """Kept from the loose set on purpose: comment-anchored ``DO NOT EDIT``
        with no other marker is specific enough on its own, and real tools emit
        it that way."""
        p = tmp_path / "c.go"
        p.write_text("// DO NOT EDIT\npackage main\n")
        assert is_likely_minified(p) is True

    def test_the_other_minification_heuristics_are_untouched(
        self, tmp_path: Path,
    ) -> None:
        """POSITIVE CONTROL for the whole file: narrowing heuristic 3 must not
        narrow heuristics 1, 2 or 4."""
        srcmap = tmp_path / "t.js"
        srcmap.write_text("var a=1;\n//# sourceMappingURL=t.js.map\n")
        assert is_likely_minified(srcmap) is True
        webpack = tmp_path / "bundle.js"
        webpack.write_text("var x = 1;\n__webpack_require__(0);\n")
        assert is_likely_minified(webpack) is True
        dense = tmp_path / "min.js"
        dense.write_text("var " + "a=1;" * 200 + "\n")
        assert is_likely_minified(dense) is True


class TestTheScopeIsTheHEADERBlock:
    """The third half-of-the-rule, and the one a first cut got wrong.

    Scanning the whole ``_HEADER_SCAN_BYTES`` head for an anchored marker
    passed every test above and, on a five-repository sweep, newly classified
    three FIRST-PARTY files as generated. All three are pinned here as the
    shapes that must not fire.
    """

    def test_prose_in_a_comment_is_still_prose(self, tmp_path: Path) -> None:
        """From ``test_max_tier.py:106`` in this repository — INV-bokim's own
        defect wearing a comment instead of a docstring."""
        p = tmp_path / "t.py"
        p.write_text(
            "import os\n\n\ndef test_thing():\n"
            '    # dir IS discovered and classified tier 4 via its\n'
            '    # "DO NOT EDIT" header, so the survey drops it\n'
            "    return os.getcwd()\n"
        )
        assert is_likely_minified(p) is False
        assert _has_generated_header(p) is False

    def test_a_per_method_stub_marker_does_not_condemn_the_file(
        self, tmp_path: Path,
    ) -> None:
        """From clover's ``BaseToggleActionDelegate.java:38``. Eclipse writes
        ``// TODO Auto-generated method stub`` inside a method body; it says
        nothing about the file, and the file is hand-written."""
        p = tmp_path / "T.java"
        p.write_text(
            "package com.example;\n\npublic class T {\n"
            "    public void run() {\n"
            "        // TODO Auto-generated method stub\n"
            "    }\n}\n"
        )
        assert is_likely_minified(p) is False
        assert _has_generated_header(p) is False

    def test_a_declaration_under_a_licence_header_DOES_fire(
        self, tmp_path: Path,
    ) -> None:
        """THE CONTROL that stops the fix above from being "never look past
        line five". From http4s's ``MimeDB.scala``, which is genuinely
        generated and carries its declaration at line 17, under a 15-line
        Apache notice."""
        p = tmp_path / "MimeDB.scala"
        p.write_text(
            "/*\n"
            + " * Copyright 2013 http4s.org\n"
            + " *\n"
            + " * Licensed under the Apache License, Version 2.0.\n"
            + " *\n" * 10
            + " */\n\n"
            "// Autogenerated file, don't edit\n"
            "package org.http4s\n\n"
            "private[http4s] trait MimeDB {}\n"
        )
        assert is_likely_minified(p) is True
        assert _has_generated_header(p) is True

    def test_the_block_ends_at_the_first_line_of_code(
        self, tmp_path: Path,
    ) -> None:
        """The boundary itself, asserted directly rather than only through the
        three cases above."""
        from hypergumbo_core.supply_chain import _leading_comment_block

        text = "# a\n\n# b\nimport os\n# @generated\n"
        assert _leading_comment_block(text) == "# a\n\n# b"

    def test_an_unprefixed_block_comment_interior_ends_the_block(
        self, tmp_path: Path,
    ) -> None:
        """The stated residual, pinned so it is a decision and not a surprise:
        a bare ``/*`` followed by unprefixed prose ends the block there, so a
        marker below it is missed. That errs toward KEEPING symbols, which is
        the direction INV-bokim was filed about."""
        p = tmp_path / "T.java"
        p.write_text("/*\nCopyright someone\n@generated by a tool\n*/\nclass T {}\n")
        assert is_likely_minified(p) is False
