# SPDX-License-Identifier: AGPL-3.0-or-later
"""A boundary anchor must name the file it stands for, not a shared placeholder.

WHAT WAS BROKEN (INV-rozob), reproduced in THREE LINES of Python on the shipped
CLI at dev bbd1635dcc::

    \"\"\"@generated\"\"\"

    from datetime import date

The import edge's ``src`` read ``python:<external>:0-0:file:external_symbol`` —
no path, span ``0-0``, kind ``external_symbol``. A reader has no file to open,
so the edge can be neither confirmed nor refuted; a taint flow seeded from one
names no place, which is the form the item was filed in (19 of 104 adjudicated
flows in measurement 0001, every one labelled UNADJUDICABLE by two independent
readers). Worse than pathless: EVERY such file in a language landed on that ONE
id, because ``make_file_id`` puts the literal ``"file"`` in the name slot, so
the node was also a many-to-one bucket.

THE CHAIN, each step verified rather than assumed:

1. ``supply_chain.is_likely_minified`` heuristic 3 matches
   ``(Generated by|@generated|DO NOT EDIT)`` case-insensitively anywhere in the
   first five lines, with NO comment anchor — so a docstring trips it.
2. The file is classified tier 4 (DERIVED). **This classification is correct**
   and is not what the fix changes: the real-world files that reach this state
   (three in sqlalchemy, two in knex, two in sops, one in poetry) genuinely are
   generated.
3. ``cli.py``'s tier filter drops the file Symbol, while DELIBERATELY KEEPING
   its edges (WI-pozur / ADR-0043 C2) so the dependency fact survives.
4. ``ir._dedupe_key`` then discarded the path for the now-dangling
   ``kind="file"`` src, on the stated grounds that it was "a per-reference
   filesystem path with no semantic identity". That sentence was the defect.

THE FIX NAMES THE FILE; IT DOES NOT DROP THE EDGE. Dropping the edge was tried
first and is WRONG — it deletes the dependency fact WI-pozur deliberately kept,
and ``test_phase_de_reorder.py::TestDanglingSourceClosed::test_pb2_import_srcs_
resolved`` fails loudly on it. That test working as designed is what redirected
this fix, and it is worth stating: the two items are in tension only if you read
INV-rozob as "the edge should not exist" rather than "the anchor should name a
place".

MEASURED ON UNMODIFIED UPSTREAM REPOS at HEAD, arm A: sqlalchemy collapsed 3
files onto one node carrying 149 edges (120 imports, 28 calls, 1 instantiates);
knex 2 files / 12 edges; sops 2 files / 11 edges (protobuf ``.pb.go``); poetry
1 file / 5 edges; httpx 0 — three languages, where the item recorded the defect
as JavaScript-only and "NOT LOCALISED".
"""

import json
from pathlib import Path

import pytest

from hypergumbo_core.cli import run_behavior_map

COLLAPSED_ID = "python:<external>:0-0:file:external_symbol"


@pytest.fixture
def generated_and_plain_repo(tmp_path: Path) -> Path:
    """One genuinely-generated file and one ordinary one, both importing.

    The plain file is load-bearing: without it the repo has no surviving edges
    at all and every assertion below would hold vacuously.
    """
    repo = tmp_path / "repo"
    (repo / "src").mkdir(parents=True)
    (repo / "src" / "gen.py").write_text(
        '"""@generated"""\n\nfrom datetime import date\n\n\n'
        "def stamp():\n    return date.today()\n"
    )
    (repo / "src" / "plain.py").write_text(
        "import os\n\n\ndef where():\n    return os.getcwd()\n"
    )
    return repo


@pytest.fixture
def two_generated_repo(tmp_path: Path) -> Path:
    """Two tier-dropped files, so the MANY-TO-ONE half of the defect is testable.

    Pathlessness and sharing are different failures: naming each anchor after its
    file fixes both, but a fix that gave every file one shared *named* id would
    pass the pathless assertions and still lose attribution.
    """
    repo = tmp_path / "two"
    (repo / "src").mkdir(parents=True)
    (repo / "src" / "gen_a.py").write_text('"""@generated"""\n\nfrom datetime import date\n')
    (repo / "src" / "gen_b.py").write_text('"""@generated"""\n\nimport os\n')
    return repo


def _survey(repo: Path, out: Path, **kw) -> dict:
    run_behavior_map(repo, out, include_sketch_precomputed=False, **kw)
    return json.loads(out.read_text())


class TestTheCollapse:

    def test_no_edge_is_anchored_on_the_shared_placeholder(
        self, generated_and_plain_repo: Path, tmp_path: Path
    ) -> None:
        """The defect verbatim: an anchor with no path."""
        data = _survey(generated_and_plain_repo, tmp_path / "out.json")
        anchored = [e for e in data["edges"] if e["src"] == COLLAPSED_ID]
        assert anchored == [], (
            f"{len(anchored)} edge(s) anchored on a placeholder with no path"
        )

    def test_the_placeholder_node_is_not_minted_at_all(
        self, generated_and_plain_repo: Path, tmp_path: Path
    ) -> None:
        """No consumer should have to learn to ignore this id."""
        data = _survey(generated_and_plain_repo, tmp_path / "out.json")
        assert COLLAPSED_ID not in {n["id"] for n in data["nodes"]}

    def test_the_anchor_names_the_generated_file(
        self, generated_and_plain_repo: Path, tmp_path: Path
    ) -> None:
        """The positive half: the edge SURVIVES (WI-pozur) and its src is a
        location a reader can open."""
        data = _survey(generated_and_plain_repo, tmp_path / "out.json")
        gen_edges = [
            e for e in data["edges"]
            if "gen.py" in e["src"] and e["type"] == "imports"
        ]
        assert gen_edges, "the generated file's import edge was dropped"
        assert all("gen.py" in e["src"] for e in gen_edges)

    def test_two_generated_files_do_not_share_one_anchor(
        self, two_generated_repo: Path, tmp_path: Path
    ) -> None:
        """THE MANY-TO-ONE HALF, which the pathlessness assertions alone do not
        cover. Both files are tier-dropped; before the fix both edges anchored on
        the SAME id, so a reader could not tell which file imported what. This is
        the assertion that fails if someone reintroduces any per-language
        collapse key."""
        data = _survey(two_generated_repo, tmp_path / "out.json")
        srcs = {e["src"] for e in data["edges"] if e["type"] == "imports"}
        gen_srcs = {s for s in srcs if "gen" in s}
        assert len(gen_srcs) == 2, f"expected one anchor per file, got {gen_srcs}"

    def test_every_surviving_edge_src_resolves_to_a_node(
        self, generated_and_plain_repo: Path, tmp_path: Path
    ) -> None:
        """The general invariant: a src must be in the node set.

        THIS TEST DID NOT CATCH THE DEFECT AND IS NOT CLAIMED TO. It passed
        before the fix, because boundary synthesis MINTS the placeholder node —
        so the graph was internally consistent while pointing at a symbol with
        no path. It is kept as a guard against a src left truly dangling
        (WI-pozur's G2 property), and it is written down that it is not the pin
        for this item, so nobody reads a green tick here as coverage of
        INV-rozob. The assertions above are the pins."""
        data = _survey(generated_and_plain_repo, tmp_path / "out.json")
        node_ids = {n["id"] for n in data["nodes"]}
        dangling = sorted({e["src"] for e in data["edges"]} - node_ids)
        assert dangling == [], f"edge srcs with no node: {dangling}"


class TestItDoesNotOverReach:
    """Positive controls. An ordinary file must be untouched."""

    def test_the_ordinary_file_keeps_its_real_file_symbol(
        self, generated_and_plain_repo: Path, tmp_path: Path
    ) -> None:
        """``plain.py`` is tier 1: it keeps a genuine ``kind="file"`` Symbol and
        is NOT turned into a boundary node."""
        data = _survey(generated_and_plain_repo, tmp_path / "out.json")
        plain = [
            n for n in data["nodes"]
            if n.get("path") == "src/plain.py" and n.get("kind") == "file"
        ]
        assert plain, "the ordinary file lost its file Symbol"
        srcs = [e["src"] for e in data["edges"] if e["type"] == "imports"]
        assert any("plain.py" in s and s.endswith(":file:file") for s in srcs)

    def test_max_tier_4_keeps_the_generated_file_as_a_real_symbol(
        self, generated_and_plain_repo: Path, tmp_path: Path
    ) -> None:
        """Asking for tier 4 asks for the generated file. Its real Symbol comes
        back and the edge anchors on THAT, not on a boundary node — which shows
        the boundary anchor is a consequence of filtering, not of the file."""
        data = _survey(generated_and_plain_repo, tmp_path / "out4.json", max_tier=4)
        node_ids = {n["id"] for n in data["nodes"]}
        assert COLLAPSED_ID not in node_ids
        real = [n for n in node_ids if "gen.py" in n and n.endswith(":file:file")]
        assert real, "the generated file's Symbol should be present at tier 4"
        assert any(e["src"] in real for e in data["edges"])
