# SPDX-License-Identifier: AGPL-3.0-or-later
"""The two hand-maintained linker-count declarations must equal the live registry.

``docs/ARCHITECTURE.md`` is regenerated by ``scripts/generate-architecture`` and
its linker inventory is already pinned by
``tests/test_generate_architecture_linker_inventory.py``. The other two places a
reader learns how many linkers exist — the ``docs/hypergumbo-spec.md`` §7
sentence and the ``docs/LINKERS.md`` ``**Count:**`` line — are typed by hand and
regenerated by nothing. They were correct when this test was written and would
have stayed correct only for as long as whoever added linker 62 remembered two
prose sentences in two files.

This is the same class of drift that had already happened twice. ADR-0012 still
described "45 linkers" and "24 linkers" long after the catalogue reached 61, and
the ``generate-architecture`` module scan skipped underscore-prefixed filenames
until 2026-08-19, so the generated count read 60 against a registry of 61.

**Why this keys on anchored sites rather than on the phrase "N linkers".** That
phrase is overwhelmingly used for *subsets*: the spec's own §11 says "explicitly
by Tier 2 (16 linkers)", ``docs/LINKERS.md`` says "21 linkers currently implement
this contract", ADR-0015 names 4, ADR-0031 names 10 / 8 / 4. A gate matching the
bare phrase would be a false-positive machine, and a gate aimed at a *name*
rather than at the *thing* is how a comfortable zero gets mistaken for evidence.
So each declaration is located by an anchor unique to it, and a site that goes
**missing** is reported exactly like a site that is **wrong** — otherwise the gate
could be satisfied by deleting the sentence it guards.

**Why the denominator is ``cli.py``'s import path.** Linkers register as an
import side effect, and production registers them through the explicit
``import hypergumbo_core.linkers.<mod>`` block in ``cli.py``. Counting the
directory's ``*.py`` files instead would answer a different question and get a
different number: ``linkers/_third_party_bases.py`` registers a linker
(``django-third-party-dispatch-linker``) whose name does not match its module,
which is precisely the discrepancy that made the generated count read 60.

The three positive controls exist because a pinning assertion that cannot be
shown to fire is indistinguishable from one that matches nothing.
"""

from __future__ import annotations

import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
SPEC = REPO_ROOT / "docs" / "hypergumbo-spec.md"
LINKERS_MD = REPO_ROOT / "docs" / "LINKERS.md"

# Anchored to the §7 hand-off sentence that sends the reader to LINKERS.md.
SPEC_DECLARATION = re.compile(r"full catalog of (\d+) linkers")

# Anchored to the LINKERS.md summary line, which also publishes the breakdown.
LINKERS_MD_DECLARATION = re.compile(
    r"\*\*Count:\*\*\s+(\d+)\s+linkers\s+—\s+"
    r"Protocol\s+(\d+),\s+Bridge\s+(\d+),\s+"
    r"Framework\s+(\d+),\s+Infrastructure\s+(\d+)"
)


def _registered_linker_count() -> int:
    """Linkers registered through the import path production actually uses."""
    import hypergumbo_core.cli  # registers every linker as an import side effect

    from hypergumbo_core.linkers.registry import list_registered

    return len(list_registered())


def check_declarations(spec_text: str, linkers_md_text: str, live: int) -> list[str]:
    """Return one problem string per stale, missing, or incoherent declaration."""
    problems: list[str] = []

    spec_hits = SPEC_DECLARATION.findall(spec_text)
    if len(spec_hits) != 1:
        problems.append(
            f"docs/hypergumbo-spec.md: expected exactly one "
            f"{SPEC_DECLARATION.pattern!r} declaration, found {len(spec_hits)}"
        )
    elif int(spec_hits[0]) != live:
        problems.append(
            f"docs/hypergumbo-spec.md declares {spec_hits[0]} linkers; "
            f"the registry has {live}"
        )

    md_hits = LINKERS_MD_DECLARATION.findall(linkers_md_text)
    if len(md_hits) != 1:
        problems.append(
            f"docs/LINKERS.md: expected exactly one '**Count:** N linkers — "
            f"Protocol .., Bridge .., Framework .., Infrastructure ..' line, "
            f"found {len(md_hits)}"
        )
    else:
        total, *subs = (int(v) for v in md_hits[0])
        if total != live:
            problems.append(
                f"docs/LINKERS.md declares {total} linkers; the registry has {live}"
            )
        if sum(subs) != total:
            names = ("Protocol", "Bridge", "Framework", "Infrastructure")
            breakdown = ", ".join(f"{n} {v}" for n, v in zip(names, subs, strict=True))
            problems.append(
                f"docs/LINKERS.md subcategories ({breakdown}) sum to {sum(subs)}, "
                f"not the declared total {total}"
            )

    return problems


def test_live_tree_declarations_match_the_registry() -> None:
    """The pin: both hand-maintained sites state the live linker count."""
    problems = check_declarations(
        SPEC.read_text(encoding="utf-8"),
        LINKERS_MD.read_text(encoding="utf-8"),
        _registered_linker_count(),
    )
    assert not problems, "linker-count drift:\n  " + "\n  ".join(problems)


def test_positive_control_a_stale_count_is_reported() -> None:
    """A wrong number in either file fails the gate — not just the spec's."""
    spec_stale = check_declarations(
        "…for the full catalog of 45 linkers grouped by subcategory…",
        "**Count:** 61 linkers — Protocol 11, Bridge 10, "
        "Framework 32, Infrastructure 8.",
        61,
    )
    assert any("spec.md declares 45" in p for p in spec_stale), spec_stale

    md_stale = check_declarations(
        "…for the full catalog of 61 linkers grouped by subcategory…",
        "**Count:** 45 linkers — Protocol 11, Bridge 10, "
        "Framework 16, Infrastructure 8.",
        61,
    )
    assert any("LINKERS.md declares 45" in p for p in md_stale), md_stale


def test_positive_control_a_deleted_declaration_is_reported() -> None:
    """Removing the guarded sentence must fail, not silently satisfy the gate."""
    problems = check_declarations("no count here", "no count line here", 61)
    assert len(problems) == 2, problems
    assert any("hypergumbo-spec.md" in p and "found 0" in p for p in problems)
    assert any("LINKERS.md" in p and "found 0" in p for p in problems)


def test_positive_control_subcategories_must_sum_to_the_total() -> None:
    """A total bumped without touching the breakdown is incoherent, and caught."""
    problems = check_declarations(
        "…for the full catalog of 61 linkers grouped by subcategory…",
        "**Count:** 61 linkers — Protocol 11, Bridge 10, "
        "Framework 31, Infrastructure 8.",
        61,
    )
    assert any("sum to 60, not the declared total 61" in p for p in problems), problems
