#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Can each catalogued I/O primitive be REACHED from an idiomatic call site?

THE INVARIANT UNDER TEST is INV-linub's statement verbatim: *a catalogued I/O
call site must reach its catalogue entry regardless of receiver syntax*. Every
prior measurement of it has been indirect — count sinks, count edges, count
escapes — and indirect counts cannot separate "the catalogue is thin" from
"the catalogue is fine and nothing can reach it". This instrument closes that
by generating a call site for EVERY entry in a language's catalogue and asking
production whether a boundary comes back.

WHY GENERATE THE FIXTURE FROM THE CATALOGUE ITSELF. A hand-written fixture
measures the primitives someone remembered, and it silently stops covering new
entries the day one is added. Reading ``load_catalog(language).primitives`` and
emitting one call site per entry means the probe's denominator IS the shipped
catalogue and cannot drift from it.

MORE THAN ONE CALL FORM, AND THAT IS THE POINT. ``import os; os.makedirs(p)``
and ``from os import makedirs; makedirs(p)`` are both idiomatic and they
exercise different resolution paths — the first leaves the module in the
receiver, the second erases it. A single-form probe reports "reachable" for a
primitive that half of real code cannot reach. Each entry is therefore emitted
once per form and scored per form, and the output names the forms rather than
assuming Python's pair (``_FORMS``): Go has ONE idiomatic form, and Java's pair
is instance-vs-static, not dotted-vs-bare. A verdict is the set of forms that
attributed, with ``NEITHER`` when none did.

THE FIXTURE SHAPE CAN DOMINATE THE ANSWER, and this file has the receipt.
Emitting JavaScript's ``require`` INSIDE the probe function attributed 4 of 187
primitives; hoisting the identical call to a module-scope ``const m =
require('fs')`` attributed 182. Same catalogue, same call, 35x apart. Whenever a
per-language emitter is added or changed, re-read what shape it is actually
generating before believing the number it produces.

THE PROBE MUST NOT ANNOUNCE ITSELF AS GENERATED. ``supply_chain``'s loose
generated-file heuristic matches ``/(Generated by|@generated|DO NOT EDIT)/i`` in
a file's first five lines and classifies the file ``Tier.DERIVED``, which for Go
drops it from analysis entirely. The first Go run of this instrument therefore
reported 0 of 210 reachable — a fabricated 100% catalogue gap — and only the
positive control below stopped it shipping. See INV-pogob.

"ATTRIBUTED", NOT "REACHABLE", AND THE DISTINCTION IS NOT PEDANTIC. The verdict
asks whether production named the CALLING FUNCTION as the chain's
``io_edge_src``. A chain can exist and still score ``NEITHER`` when it is
anchored somewhere else — every one of this probe's own residual entries is,
carrying ``src=python:<external>:0-0:file:external_symbol`` with
``entry_points=[]``. An earlier revision of this file
called that bucket "UNREACHABLE", which reads as "hypergumbo cannot see this
primitive" when the truth is "hypergumbo sees it and cannot say who called it".
Those are different defects with different owners, so the run now prints the
anchor-kind breakdown and counts the anchored-elsewhere cases separately
instead of folding them into a gap number.

WHAT THIS DOES *NOT* MEASURE, stated because the number invites over-reading.
It is a LOWER BOUND on attribution gaps in the idiomatic direction only. A
primitive scoring BOTH here can still be missed through an alias, a re-export,
a conditional import or a wrapped receiver; a primitive scoring NEITHER is
unattributed for these two forms and no claim is made about others. It is an
attribution probe, not a recall estimate on real code — the real-code number
for the change that motivated it was ZERO edges on two repos while this probe
moved 78 primitives.

NOT EVERY ENTRY IS EXPRESSIBLE, and those are reported separately rather than
counted as failures. ``builtins.open`` is idiomatically a bare ``open(...)``
with no import; ``file.write`` names no importable type. Folding an
inexpressible entry into the failure bucket would inflate the gap with the
probe's own limitation, which is the reverse of the error this file exists to
avoid.

POSITIVE CONTROL, printed before any verdict: at least one entry must score
reachable. A run where nothing resolves is measuring a broken fixture or a
broken pipeline, not a catalogue gap, and says so instead of reporting 100%.

Usage:
    scripts/measure-catalogue-reach.py LANGUAGE [--workdir DIR] [--json OUT]
"""
from __future__ import annotations

import argparse
import collections
import contextlib
import io
import json
import pathlib
import shutil
import sys
import tempfile
from typing import Any

from hypergumbo_core.io_boundary import load_catalog

# Entries whose idiomatic call site has no import at all, or whose module slot
# names no importable thing. Enumerated as PREFIXES so the list stays short and
# its intent is readable; anything matching is reported as inexpressible.
_INEXPRESSIBLE_MODULES = ("builtins", "file", "self", "cls")


def _safe(text: str) -> str:
    return "".join(ch if ch.isalnum() else "_" for ch in text)


def _py_call_sites(prim: Any) -> tuple[str, str] | None:
    """(dotted-form body, bare-form body) for *prim*, or None if inexpressible.

    ``module`` means different things per kind and the generator has to respect
    that: for a ``function`` it is the importable module, for a ``method`` it is
    the TYPE the method hangs off (``pathlib.Path``, ``socket.socket``), which
    is itself imported from its parent module and then constructed.
    """
    module, name, kind = prim.module, prim.name, prim.kind
    if not module or not name:
        return None
    if module.split(".")[0] in _INEXPRESSIBLE_MODULES:
        return None
    if "." in module:
        parent, leaf = module.rsplit(".", 1)
    else:
        parent, leaf = module, ""

    if kind == "function":
        dotted = f"    import {module}\n    return {module}.{name}(a, b)\n"
        bare = f"    from {module} import {name}\n    return {name}(a, b)\n"
    elif kind == "method":
        # The receiver is constructed from the type named in the module slot.
        if leaf:
            dotted = (f"    import {parent}\n"
                      f"    return {parent}.{leaf}(a).{name}(b)\n")
            bare = (f"    from {parent} import {leaf}\n"
                    f"    return {leaf}(a).{name}(b)\n")
        else:
            dotted = f"    import {module}\n    return {module}(a).{name}(b)\n"
            bare = dotted
    elif kind == "attribute":
        dotted = f"    import {module}\n    return {module}.{name}\n"
        bare = f"    from {module} import {name}\n    return {name}\n"
    else:  # pragma: no cover - kind axis is closed; guard for a new value
        return None
    return dotted, bare


#: Per-language form vocabulary. The two Python forms were `dotted` and `bare`
#: because `import M; M.f()` and `from M import f; f()` exercise different
#: resolution paths. Other languages do NOT have that same pair, and pretending
#: they do is how a probe reports a language-shaped result as a catalogue gap:
#:
#:   go          `dotted`  = `(&pkg.T{}).f(a)`   `twostep` = `var r pkg.T`
#:               followed by `r.f(a)`. Go has no `from M import f`, so the axis
#:               that matters is not dotted-vs-bare but HOW THE RECEIVER IS
#:               SPELLED — and the two spellings are not equivalent to the
#:               analyzer. go.py types a receiver only when the operand is a
#:               bare identifier, so the parenthesized composite literal
#:               `(&http.Client{}).Get(u)` carries NO receiver evidence and
#:               mints `go:external:0-0:Get:unresolved`, while every idiomatic
#:               spelling of the same call mints `go:net/http:0-0:Get`.
#:               Scoring Go on the parenthesized form ALONE is what produced
#:               this instrument's "100% of Go's method-kind surface is
#:               unattributed" result — a fixture artefact, not a catalogue
#:               gap. Both forms are kept: the parenthesized one is a real
#:               (if rarer) Go spelling and dropping it would hide the
#:               analyzer hole instead of measuring it.
#:   javascript  `dotted` = `const m = require('M'); m.f()`
#:               `bare`   = `const { f } = require('M'); f()`
#:               A self-named global (`fetch`) has only the bare form.
#:   java        `instance` = `new T(a).f(b)`   `static` = `T.f(a, b)`
#:               NOT dotted/bare — the axis that matters in Java is whether the
#:               call is on an instance or on the class, and that is exactly
#:               INV-suril's question: java.yaml declares every
#:               java.nio.file.Files entry `methods:` while Files' methods are
#:               static, so an instance-only probe would score them all missing
#:               for the wrong reason.
_FORMS: dict[str, tuple[str, ...]] = {
    "python": ("dotted", "bare"),
    "go": ("dotted", "twostep"),
    "javascript": ("dotted", "bare"),
    "typescript": ("dotted", "bare"),
    "java": ("instance", "static"),
}


def _go_call_sites(prim: Any) -> tuple[dict[str, str], set[str]] | None:
    """({form: statement}, {import paths}) for Go, or None if inexpressible.

    Go imports are FILE-scoped, so the bodies cannot carry their own import the
    way Python's can; the needed paths come back separately and are emitted in
    one block. The package identifier is the last path segment, which holds for
    every stdlib path in the catalogue (`net/http` -> `http`, `os/exec` ->
    `exec`).

    Syntactic validity is enough and type validity is not, because Go is
    analysed with tree-sitter and never compiled. `os.WriteFile(a, b)` with
    untyped params would not build; it parses, and parsing is what the boundary
    map reads.
    """
    module, name, kind = prim.module, prim.name, prim.kind
    if not module or not name:
        return None
    if kind == "function":
        pkg = module.rsplit("/", 1)[-1]
        return {"dotted": f"\t_ = {pkg}.{name}(a, b)\n"}, {module}
    if kind == "method":
        # module slot is package/path.Type — split on the LAST dot, which is
        # the type boundary, not on "/" which is the path separator.
        if "." not in module:
            return None
        parent, leaf = module.rsplit(".", 1)
        pkg = parent.rsplit("/", 1)[-1]
        # TWO RECEIVER SPELLINGS, AND THE DIFFERENCE IS THE MEASUREMENT.
        # `dotted` is a parenthesized composite literal. go.py only types a
        # receiver whose operand node is a bare `identifier`, so this spelling
        # skips receiver typing entirely and lands on the `external` module
        # placeholder — which then fails the module filter and dies in the
        # io-boundary F3 method gate. `twostep` declares the receiver first,
        # which is what idiomatic Go looks like and what recovers the package.
        # Emitting only the first form scored every method entry NEITHER and
        # was read as a catalogue gap for a full measurement cycle.
        return {
            "dotted": f"\t_ = (&{pkg}.{leaf}{{}}).{name}(a)\n",
            "twostep": f"\tvar r {pkg}.{leaf}\n\t_ = r.{name}(a)\n",
        }, {parent}
    if kind == "attribute":
        pkg = module.rsplit("/", 1)[-1]
        return {"dotted": f"\t_ = {pkg}.{name}\n"}, {module}
    return None  # pragma: no cover - kind axis is closed


def _report_go_import_paths(prims: list[Any]) -> None:
    """Disclose the import paths the Go fixture synthesised, and why it matters.

    THE FIXTURE'S IMPORT PATH IS THE CATALOGUE'S OWN MODULE SLOT, and for a
    third-party entry that slot is a package IDENTIFIER rather than a module
    PATH. ``gin.Context`` yields ``import ("gin")`` — a line no Go program
    contains. The entry then scores reachable against a module hint production
    can never emit, because go.py reports the real import path:

        lookup_with_module("JSON", "github.com/gin-gonic/gin", cc="method")
            -> None
        lookup_with_module("JSON", "gin",                      cc="method")
            -> gin.Context.JSON

    So a rise in this instrument's Go number can mean the catalogue got more
    reachable OR that the fixture got better at agreeing with itself, and the
    two are indistinguishable from the rate alone.

    THIS PRINTS THE PATHS RATHER THAN CLASSIFYING THEM, and that is deliberate.
    Separating a real single-segment stdlib path (``os``, ``net``, ``testing``)
    from a fabricated one (``gin``, ``echo``) needs Go's stdlib package list,
    which is not derivable from the catalogue — go.yaml marks the framework
    rows with a YAML COMMENT and nothing machine-readable. Shipping a guessed
    classifier here would put a wrong verdict in the headline; showing the
    reader the actual imports lets them see the fabrication directly.
    """
    single, pathlike = set(), set()
    for prim in prims:
        sites = _go_call_sites(prim)
        if sites is None:
            continue
        for path in sites[1]:
            (pathlike if "/" in path else single).add(path)
    print("\n--- go fixture import paths (read before believing the rate) ---")
    print(f"  path-shaped, faithful to real Go  : {len(pathlike)}  "
          f"{sorted(pathlike)[:6]}...")
    print(f"  single-segment, VERIFY BY EYE     : {len(single)}  "
          f"{sorted(single)}")
    print("  A single-segment entry is faithful only if it is genuinely a "
          "stdlib package.\n  Any that is not (gin, echo, fiber, grpc ...) "
          "scores reachable against an import\n  no Go program writes — see "
          "this function's docstring.")


def _js_call_sites(prim: Any, alias: str) -> dict[str, str] | None:
    """{form: body} for JavaScript/TypeScript, or None if inexpressible.

    THE `dotted` FORM PUTS ITS `require` AT MODULE SCOPE, not inside the
    function, and that is the whole point of the form. `const fs =
    require('fs')` at the top of a file followed by `fs.readFileSync(p)` inside
    a function is the dominant JS idiom; a function-local `require` is a
    different (and rarer) shape, and measuring the rare one would answer a
    question nobody asked. The caller supplies the module-scope `alias`.
    """
    module, name, kind = prim.module, prim.name, prim.kind
    if not module or not name:
        return None
    if module == name:
        # A self-named global: the catalogue writes `module: fetch,
        # functions: [fetch]` for `fetch(url)`. There is nothing to require.
        return {"bare": f"  return {name}(a, b);\n"}
    if kind in ("function", "attribute"):
        return {
            "dotted": f"  return {alias}.{name}(a, b);\n",
            "bare": f"  const {{ {name} }} = require({module!r});\n"
                    f"  return {name}(a, b);\n",
        }
    if kind == "method":
        if "." in module:
            parent, leaf = module.rsplit(".", 1)
            return {
                "dotted": f"  return new {alias}.{leaf}(a).{name}(b);\n",
                "bare": f"  const {{ {leaf} }} = require({parent!r});\n"
                        f"  return new {leaf}(a).{name}(b);\n",
            }
        return {
            "dotted": f"  return {alias}.{name}(b);\n",
            "bare": f"  const {{ {name} }} = require({module!r});\n"
                    f"  return {name}(b);\n",
        }
    return None  # pragma: no cover - kind axis is closed


def _java_call_sites(prim: Any) -> tuple[dict[str, str], set[str]] | None:
    """({form: statement}, {import lines}) for Java, or None if inexpressible.

    Both an INSTANCE form and a STATIC form are emitted for every entry,
    because the catalogue does not record which a class actually offers and the
    difference is load-bearing: `java.nio.file.Files` is declared `methods:`
    and every one of its methods is static (INV-suril).
    """
    module, name = prim.module, prim.name
    if not module or not name or "." not in module:
        return None
    cls = module.rsplit(".", 1)[-1]
    return (
        {
            "instance": f"        new {cls}(a).{name}(b);\n",
            "static": f"        {cls}.{name}(a, b);\n",
        },
        {f"import {module};"},
    )


def _write_fixture(language: str, prims: list[Any], root: pathlib.Path
                   ) -> tuple[dict[str, Any], list[Any]]:
    """Emit one function per (primitive, form). Returns fn-name -> primitive."""
    if root.exists():
        shutil.rmtree(root)
    root.mkdir(parents=True)
    index: dict[str, Any] = {}
    skipped: list[Any] = []
    # THE BANNER MUST NOT SAY "GENERATED BY", AND THAT IS NOT A STYLE CHOICE.
    # `supply_chain.is_likely_minified` heuristic 3 matches
    # /(Generated by|@generated|DO NOT EDIT)/i anywhere in a file's first five
    # lines and classifies the file Tier.DERIVED. For GO that drops the file
    # from analysis entirely: the identical fixture scores 2 boundaries with a
    # neutral header and ZERO with "// generated by ...", which is how this
    # probe spent its first run reporting 0 of 210 Go primitives reachable —
    # a 100% miss manufactured by its own header. (Python is NOT affected by
    # the same classification, so the shipped python numbers stand; the
    # per-language asymmetry is filed separately.)
    banner = "probe fixture emitted by scripts/measure-catalogue-reach.py"

    if language in ("javascript", "typescript"):
        suffix = "js" if language == "javascript" else "ts"
        lines = [f"// {banner}\n"]
        requires: dict[str, str] = {}
        bodies_js: list[str] = []
        for i, prim in enumerate(prims):
            # The module-scope alias for the `dotted` form. A method entry's
            # module slot is Type-qualified (`X.Y`), so the require target is
            # its parent — the same split the body uses.
            req_target = prim.module
            if prim.kind == "method" and "." in (prim.module or ""):
                req_target = prim.module.rsplit(".", 1)[0]
            alias = requires.setdefault(
                req_target, f"_m{len(requires)}"
            ) if req_target else "_m0"
            sites = _js_call_sites(prim, alias)
            if sites is None:
                skipped.append(prim)
                continue
            for form, body in sites.items():
                fn = f"probe_{i}_{form}_{_safe(prim.module)}_{_safe(prim.name)}"
                index[fn] = (prim, form)
                bodies_js.append(f"\nfunction {fn}(a, b) {{\n{body}}}\n")
        for target, alias in sorted(requires.items(), key=lambda kv: kv[1]):
            lines.append(f"const {alias} = require({target!r});\n")
        lines.extend(bodies_js)
        (root / f"probe.{suffix}").write_text("".join(lines))
        return index, skipped

    if language == "go":
        # ONE FILE PER IMPORT PATH, not one file for the whole catalogue.
        # Two reasons, and the first was found the hard way: a single file
        # importing all 22 packages the catalogue names returned ZERO
        # boundaries while the same call sites split across small files return
        # them normally, so the monolithic fixture was measuring an artefact of
        # its own shape. The second is that it is simply what Go looks like —
        # a file importing `echo`, `grpc`, `syscall` and `testing` at once is
        # not an idiomatic call site and this probe exists to generate those.
        by_pkg: dict[str, list[str]] = collections.defaultdict(list)
        for i, prim in enumerate(prims):
            sites = _go_call_sites(prim)
            if sites is None:
                skipped.append(prim)
                continue
            forms, needed = sites
            path = sorted(needed)[0]
            for form, body in forms.items():
                fn = f"probe_{i}_{form}_{_safe(prim.module)}_{_safe(prim.name)}"
                index[fn] = (prim, form)
                by_pkg[path].append(
                    f"\nfunc {fn}(a, b interface{{}}) {{\n{body}}}\n"
                )
        (root / "go.mod").write_text("module probe\n\ngo 1.21\n")
        for path, fns in by_pkg.items():
            header = (f"// {banner}\npackage probe\n\n"
                      f'import (\n\t"{path}"\n)\n')
            (root / f"probe_{_safe(path)}.go").write_text(
                header + "".join(fns)
            )
        return index, skipped

    if language == "java":
        bodies = []
        import_lines: set[str] = set()
        for i, prim in enumerate(prims):
            sites = _java_call_sites(prim)
            if sites is None:
                skipped.append(prim)
                continue
            forms, needed = sites
            import_lines |= needed
            for form, body in forms.items():
                fn = f"probe_{i}_{form}_{_safe(prim.module)}_{_safe(prim.name)}"
                index[fn] = (prim, form)
                bodies.append(
                    f"\n    void {fn}(Object a, Object b) {{\n"
                    f"        try {{\n{body}        }} catch (Exception e) {{}}\n"
                    f"    }}\n"
                )
        header = (f"// {banner}\n"
                  + "".join(f"{line}\n" for line in sorted(import_lines))
                  + "\npublic class Probe {\n")
        (root / "Probe.java").write_text(header + "".join(bodies) + "}\n")
        return index, skipped

    lines = ["# generated by scripts/measure-catalogue-reach.py\n"]
    for i, prim in enumerate(prims):
        py_sites = _py_call_sites(prim)
        if py_sites is None:
            skipped.append(prim)
            continue
        dotted, bare = py_sites
        for form, body in (("dotted", dotted), ("bare", bare)):
            fn = f"probe_{i}_{form}_{_safe(prim.module)}_{_safe(prim.name)}"
            index[fn] = (prim, form)
            lines.append(f"\n\ndef {fn}(a, b):\n{body}")
    (root / "probe.py").write_text("".join(lines))
    return index, skipped


def _boundaries_for(
    root: pathlib.Path,
) -> tuple[dict[str, set[str]], "collections.Counter", set[str]]:
    """(fn-name -> primitives attributed to it, anchor-kind tally, unanchored).

    The third element is the honesty term: primitives whose chain carries NO
    entry point, so no probe function can be credited with them however the
    attribution is written.
    """
    from hypergumbo_core.cli import main

    argv = sys.argv
    sys.argv = ["hypergumbo", "io-boundaries", str(root), "--format", "json"]
    buf = io.StringIO()
    try:
        with contextlib.redirect_stdout(buf):
            with contextlib.suppress(SystemExit):
                main()
    finally:
        sys.argv = argv
    raw = buf.getvalue()
    start = raw.find("{")
    report = json.loads(raw[start:]) if start >= 0 else {}
    hits: dict[str, set[str]] = collections.defaultdict(set)
    anchors: collections.Counter = collections.Counter()
    elsewhere: set[str] = set()
    for bucket in report.get("boundaries", {}).values():
        for chain in bucket.get("chains", []):
            src = chain.get("io_edge_src", "")
            prim = chain.get("primitive", "")
            parts = src.split(":")
            if len(parts) < 2:
                continue
            # THE NAME SLOT IS THE CALLER; THE KIND SLOT IS NOT. An attributed
            # chain reads python:probe.py:0-0:<probe_fn>:external_symbol — the
            # caller sits in parts[-2] while parts[-1] says `external_symbol`
            # for every chain on this fixture. Counting parts[-1] and calling it
            # "the anchor" is what made two correct readings look contradictory
            # for an hour; both slots are therefore reported, distinctly.
            anchors[parts[-1]] += 1
            hits[parts[-2]].add(prim)
            # Java (and any language whose functions are class members) puts
            # the caller in the name slot as `Probe.probe_7_static_...`, so
            # index the last dotted segment too. Indexing only the full string
            # would score every Java entry NEITHER for a naming reason and
            # report it as a catalogue gap.
            if "." in parts[-2]:
                hits[parts[-2].rsplit(".", 1)[-1]].add(prim)
            if "probe_" not in parts[-2]:
                # Anchored to something that is not a probe function at all —
                # the residual entries all read `...:0-0:file:external_symbol`.
                elsewhere.add(prim)
    return hits, anchors, elsewhere


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("language")
    ap.add_argument(
        "--workdir",
        default=str(pathlib.Path(tempfile.gettempdir()) / "hg-catalogue-reach"),
        help="scratch dir for the generated probe fixture",
    )
    ap.add_argument("--json", dest="out")
    args = ap.parse_args()

    catalog = load_catalog(args.language)
    prims = list(catalog.primitives)
    root = pathlib.Path(args.workdir) / args.language
    index, skipped = _write_fixture(args.language, prims, root)
    print(f"language                 : {args.language}")
    print(f"catalogued primitives    : {len(prims)}")
    print(f"  ... inexpressible      : {len(skipped)} "
          f"({sorted({p.qualified_name for p in skipped})[:6]}...)")
    print(f"generated probe functions: {len(index)}")
    if args.language == "go":
        _report_go_import_paths(prims)

    hits, anchors, elsewhere = _boundaries_for(root)
    print(f"io_edge_src KIND slot     : {dict(anchors)}")
    print(f"io_edge_src NAME slots seen: {len(hits)}")
    print(f"primitives anchored to a NON-caller name: {len(elsewhere)}")
    if not hits:
        print("\n!! NOTHING RESOLVED. This is a broken fixture or a broken "
              "pipeline, not a catalogue gap. Refusing to report a 100% miss.")
        return 2

    per_prim: dict[str, set[str]] = collections.defaultdict(set)
    for fn, (prim, form) in index.items():
        # Attribution is by NAME, not merely by "some boundary appeared": a
        # probe function that resolves to a DIFFERENT primitive has not shown
        # the entry under test is reachable.
        if prim.qualified_name in hits.get(fn, ()):
            per_prim[prim.qualified_name].add(form)

    # The verdict vocabulary is per-language because the FORMS are (see
    # ``_FORMS``). A single-form language has no "BOTH"; Java's pair is
    # instance/static, not dotted/bare. Naming the forms in the output is what
    # keeps a Go result from being read against a Python legend.
    lang_forms = _FORMS.get(args.language, ("dotted", "bare"))
    all_forms = "+".join(lang_forms).upper()
    rows = []
    verdicts: collections.Counter[str] = collections.Counter()
    for prim in prims:
        if prim in skipped:
            continue
        forms = per_prim.get(prim.qualified_name, set())
        if not forms:
            verdict = "NEITHER"
        elif len(forms) == len(lang_forms):
            verdict = all_forms if len(lang_forms) > 1 else lang_forms[0].upper()
        else:
            verdict = "+".join(sorted(forms)).upper()
        verdicts[verdict] += 1
        rows.append({"primitive": prim.qualified_name, "kind": prim.kind,
                     "boundary": prim.boundary, "verdict": verdict})

    total = sum(verdicts.values())
    print(f"\n=== ATTRIBUTION over {total} expressible primitives ===")
    print(f"    forms probed for {args.language}: {', '.join(lang_forms)}")
    ordered = [all_forms] + [f.upper() for f in lang_forms] + ["NEITHER"]
    for v in dict.fromkeys(ordered):
        n = verdicts[v]
        print(f"  {v:<12}{n:>5}{100 * n / max(total, 1):>7.1f}%")
    for v, n in sorted(verdicts.items()):
        if v not in ordered:  # pragma: no cover - mixed multi-form residue
            print(f"  {v:<12}{n:>5}{100 * n / max(total, 1):>7.1f}%")

    misses = [r for r in rows if r["verdict"] == "NEITHER"]
    seen_but_unanchored = sorted(
        r["primitive"] for r in misses if r["primitive"] in elsewhere)
    if seen_but_unanchored:
        print(f"\nOF THE UNATTRIBUTED, {len(seen_but_unanchored)} DO have a "
              f"chain — anchored to a non-caller name, not missing:")
        for q in seen_but_unanchored:
            print(f"  {q}")
    if misses:
        by_kind = collections.Counter(r["kind"] for r in misses)
        by_bound = collections.Counter(r["boundary"] for r in misses)
        print(f"\nUNATTRIBUTED by kind    : {dict(by_kind)}")
        print(f"UNATTRIBUTED by boundary: {dict(by_bound.most_common(8))}")
        print("\nfirst 25 unattributed:")
        for r in misses[:25]:
            print(f"  {r['primitive']:<44}{r['kind']:<10}{r['boundary']}")

    if args.out:
        pathlib.Path(args.out).write_text(json.dumps(
            {"language": args.language, "total": len(prims),
             "inexpressible": [p.qualified_name for p in skipped],
             "anchor_kinds": dict(anchors),
             "chain_without_entry_point": sorted(elsewhere),
             "verdicts": dict(verdicts), "rows": rows}, indent=2))
        print(f"\nWrote {args.out}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
