name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pytest:
    runs-on: codeberg-small-lazy
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -e .[dev,javascript,php,c,java,elixir,rust,go,ruby,kotlin,swift,scala,lua]
      - name: Run tests
        run: |
          pytest
